// Code generated by ent, DO NOT EDIT.

package grouphealthevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the grouphealthevent type in the database.
	Label = "group_health_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldSuccess holds the string denoting the success field in the database.
	FieldSuccess = "success"
	// FieldIsProbe holds the string denoting the is_probe field in the database.
	FieldIsProbe = "is_probe"
	// FieldSemanticStarted holds the string denoting the semantic_started field in the database.
	FieldSemanticStarted = "semantic_started"
	// FieldErrorCategory holds the string denoting the error_category field in the database.
	FieldErrorCategory = "error_category"
	// FieldTtftMs holds the string denoting the ttft_ms field in the database.
	FieldTtftMs = "ttft_ms"
	// FieldTotalMs holds the string denoting the total_ms field in the database.
	FieldTotalMs = "total_ms"
	// FieldObservedAt holds the string denoting the observed_at field in the database.
	FieldObservedAt = "observed_at"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the grouphealthevent in the database.
	Table = "group_health_events"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "group_health_events"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
)

// Columns holds all SQL columns for grouphealthevent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldGroupID,
	FieldAccountID,
	FieldKind,
	FieldSuccess,
	FieldIsProbe,
	FieldSemanticStarted,
	FieldErrorCategory,
	FieldTtftMs,
	FieldTotalMs,
	FieldObservedAt,
	FieldErrorMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultKind holds the default value on creation for the "kind" field.
	DefaultKind string
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// DefaultSuccess holds the default value on creation for the "success" field.
	DefaultSuccess bool
	// DefaultIsProbe holds the default value on creation for the "is_probe" field.
	DefaultIsProbe bool
	// DefaultSemanticStarted holds the default value on creation for the "semantic_started" field.
	DefaultSemanticStarted bool
	// ErrorCategoryValidator is a validator for the "error_category" field. It is called by the builders before save.
	ErrorCategoryValidator func(string) error
	// DefaultTtftMs holds the default value on creation for the "ttft_ms" field.
	DefaultTtftMs int
	// DefaultTotalMs holds the default value on creation for the "total_ms" field.
	DefaultTotalMs int
)

// OrderOption defines the ordering options for the GroupHealthEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// BySuccess orders the results by the success field.
func BySuccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccess, opts...).ToFunc()
}

// ByIsProbe orders the results by the is_probe field.
func ByIsProbe(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsProbe, opts...).ToFunc()
}

// BySemanticStarted orders the results by the semantic_started field.
func BySemanticStarted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSemanticStarted, opts...).ToFunc()
}

// ByErrorCategory orders the results by the error_category field.
func ByErrorCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCategory, opts...).ToFunc()
}

// ByTtftMs orders the results by the ttft_ms field.
func ByTtftMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTtftMs, opts...).ToFunc()
}

// ByTotalMs orders the results by the total_ms field.
func ByTotalMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalMs, opts...).ToFunc()
}

// ByObservedAt orders the results by the observed_at field.
func ByObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedAt, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
