// Code generated by ent, DO NOT EDIT.

package grouphealthevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldGroupID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldAccountID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldKind, v))
}

// Success applies equality check predicate on the "success" field. It's identical to SuccessEQ.
func Success(v bool) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldSuccess, v))
}

// IsProbe applies equality check predicate on the "is_probe" field. It's identical to IsProbeEQ.
func IsProbe(v bool) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldIsProbe, v))
}

// SemanticStarted applies equality check predicate on the "semantic_started" field. It's identical to SemanticStartedEQ.
func SemanticStarted(v bool) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldSemanticStarted, v))
}

// ErrorCategory applies equality check predicate on the "error_category" field. It's identical to ErrorCategoryEQ.
func ErrorCategory(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldErrorCategory, v))
}

// TtftMs applies equality check predicate on the "ttft_ms" field. It's identical to TtftMsEQ.
func TtftMs(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldTtftMs, v))
}

// TotalMs applies equality check predicate on the "total_ms" field. It's identical to TotalMsEQ.
func TotalMs(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldTotalMs, v))
}

// ObservedAt applies equality check predicate on the "observed_at" field. It's identical to ObservedAtEQ.
func ObservedAt(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldObservedAt, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotIn(FieldGroupID, vs...))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotNull(FieldAccountID))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldContainsFold(FieldKind, v))
}

// SuccessEQ applies the EQ predicate on the "success" field.
func SuccessEQ(v bool) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldSuccess, v))
}

// SuccessNEQ applies the NEQ predicate on the "success" field.
func SuccessNEQ(v bool) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldSuccess, v))
}

// IsProbeEQ applies the EQ predicate on the "is_probe" field.
func IsProbeEQ(v bool) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldIsProbe, v))
}

// IsProbeNEQ applies the NEQ predicate on the "is_probe" field.
func IsProbeNEQ(v bool) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldIsProbe, v))
}

// SemanticStartedEQ applies the EQ predicate on the "semantic_started" field.
func SemanticStartedEQ(v bool) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldSemanticStarted, v))
}

// SemanticStartedNEQ applies the NEQ predicate on the "semantic_started" field.
func SemanticStartedNEQ(v bool) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldSemanticStarted, v))
}

// ErrorCategoryEQ applies the EQ predicate on the "error_category" field.
func ErrorCategoryEQ(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldErrorCategory, v))
}

// ErrorCategoryNEQ applies the NEQ predicate on the "error_category" field.
func ErrorCategoryNEQ(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldErrorCategory, v))
}

// ErrorCategoryIn applies the In predicate on the "error_category" field.
func ErrorCategoryIn(vs ...string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIn(FieldErrorCategory, vs...))
}

// ErrorCategoryNotIn applies the NotIn predicate on the "error_category" field.
func ErrorCategoryNotIn(vs ...string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotIn(FieldErrorCategory, vs...))
}

// ErrorCategoryGT applies the GT predicate on the "error_category" field.
func ErrorCategoryGT(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGT(FieldErrorCategory, v))
}

// ErrorCategoryGTE applies the GTE predicate on the "error_category" field.
func ErrorCategoryGTE(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGTE(FieldErrorCategory, v))
}

// ErrorCategoryLT applies the LT predicate on the "error_category" field.
func ErrorCategoryLT(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLT(FieldErrorCategory, v))
}

// ErrorCategoryLTE applies the LTE predicate on the "error_category" field.
func ErrorCategoryLTE(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLTE(FieldErrorCategory, v))
}

// ErrorCategoryContains applies the Contains predicate on the "error_category" field.
func ErrorCategoryContains(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldContains(FieldErrorCategory, v))
}

// ErrorCategoryHasPrefix applies the HasPrefix predicate on the "error_category" field.
func ErrorCategoryHasPrefix(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldHasPrefix(FieldErrorCategory, v))
}

// ErrorCategoryHasSuffix applies the HasSuffix predicate on the "error_category" field.
func ErrorCategoryHasSuffix(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldHasSuffix(FieldErrorCategory, v))
}

// ErrorCategoryIsNil applies the IsNil predicate on the "error_category" field.
func ErrorCategoryIsNil() predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIsNull(FieldErrorCategory))
}

// ErrorCategoryNotNil applies the NotNil predicate on the "error_category" field.
func ErrorCategoryNotNil() predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotNull(FieldErrorCategory))
}

// ErrorCategoryEqualFold applies the EqualFold predicate on the "error_category" field.
func ErrorCategoryEqualFold(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEqualFold(FieldErrorCategory, v))
}

// ErrorCategoryContainsFold applies the ContainsFold predicate on the "error_category" field.
func ErrorCategoryContainsFold(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldContainsFold(FieldErrorCategory, v))
}

// TtftMsEQ applies the EQ predicate on the "ttft_ms" field.
func TtftMsEQ(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldTtftMs, v))
}

// TtftMsNEQ applies the NEQ predicate on the "ttft_ms" field.
func TtftMsNEQ(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldTtftMs, v))
}

// TtftMsIn applies the In predicate on the "ttft_ms" field.
func TtftMsIn(vs ...int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIn(FieldTtftMs, vs...))
}

// TtftMsNotIn applies the NotIn predicate on the "ttft_ms" field.
func TtftMsNotIn(vs ...int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotIn(FieldTtftMs, vs...))
}

// TtftMsGT applies the GT predicate on the "ttft_ms" field.
func TtftMsGT(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGT(FieldTtftMs, v))
}

// TtftMsGTE applies the GTE predicate on the "ttft_ms" field.
func TtftMsGTE(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGTE(FieldTtftMs, v))
}

// TtftMsLT applies the LT predicate on the "ttft_ms" field.
func TtftMsLT(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLT(FieldTtftMs, v))
}

// TtftMsLTE applies the LTE predicate on the "ttft_ms" field.
func TtftMsLTE(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLTE(FieldTtftMs, v))
}

// TotalMsEQ applies the EQ predicate on the "total_ms" field.
func TotalMsEQ(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldTotalMs, v))
}

// TotalMsNEQ applies the NEQ predicate on the "total_ms" field.
func TotalMsNEQ(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldTotalMs, v))
}

// TotalMsIn applies the In predicate on the "total_ms" field.
func TotalMsIn(vs ...int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIn(FieldTotalMs, vs...))
}

// TotalMsNotIn applies the NotIn predicate on the "total_ms" field.
func TotalMsNotIn(vs ...int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotIn(FieldTotalMs, vs...))
}

// TotalMsGT applies the GT predicate on the "total_ms" field.
func TotalMsGT(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGT(FieldTotalMs, v))
}

// TotalMsGTE applies the GTE predicate on the "total_ms" field.
func TotalMsGTE(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGTE(FieldTotalMs, v))
}

// TotalMsLT applies the LT predicate on the "total_ms" field.
func TotalMsLT(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLT(FieldTotalMs, v))
}

// TotalMsLTE applies the LTE predicate on the "total_ms" field.
func TotalMsLTE(v int) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLTE(FieldTotalMs, v))
}

// ObservedAtEQ applies the EQ predicate on the "observed_at" field.
func ObservedAtEQ(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldObservedAt, v))
}

// ObservedAtNEQ applies the NEQ predicate on the "observed_at" field.
func ObservedAtNEQ(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldObservedAt, v))
}

// ObservedAtIn applies the In predicate on the "observed_at" field.
func ObservedAtIn(vs ...time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIn(FieldObservedAt, vs...))
}

// ObservedAtNotIn applies the NotIn predicate on the "observed_at" field.
func ObservedAtNotIn(vs ...time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotIn(FieldObservedAt, vs...))
}

// ObservedAtGT applies the GT predicate on the "observed_at" field.
func ObservedAtGT(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGT(FieldObservedAt, v))
}

// ObservedAtGTE applies the GTE predicate on the "observed_at" field.
func ObservedAtGTE(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGTE(FieldObservedAt, v))
}

// ObservedAtLT applies the LT predicate on the "observed_at" field.
func ObservedAtLT(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLT(FieldObservedAt, v))
}

// ObservedAtLTE applies the LTE predicate on the "observed_at" field.
func ObservedAtLTE(v time.Time) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLTE(FieldObservedAt, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.FieldContainsFold(FieldErrorMessage, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupHealthEvent) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupHealthEvent) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupHealthEvent) predicate.GroupHealthEvent {
	return predicate.GroupHealthEvent(sql.NotPredicates(p))
}
