// Code generated by ent, DO NOT EDIT.

package grouphealthstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the grouphealthstate type in the database.
	Label = "group_health_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldLastProbeAt holds the string denoting the last_probe_at field in the database.
	FieldLastProbeAt = "last_probe_at"
	// FieldLastSuccessAt holds the string denoting the last_success_at field in the database.
	FieldLastSuccessAt = "last_success_at"
	// FieldNextProbeAt holds the string denoting the next_probe_at field in the database.
	FieldNextProbeAt = "next_probe_at"
	// FieldFailureCount holds the string denoting the failure_count field in the database.
	FieldFailureCount = "failure_count"
	// FieldProbeTtftMs holds the string denoting the probe_ttft_ms field in the database.
	FieldProbeTtftMs = "probe_ttft_ms"
	// FieldProbeAvailability6h holds the string denoting the probe_availability_6h field in the database.
	FieldProbeAvailability6h = "probe_availability_6h"
	// FieldProbeTtftAvgMs holds the string denoting the probe_ttft_avg_ms field in the database.
	FieldProbeTtftAvgMs = "probe_ttft_avg_ms"
	// FieldProbeTtftP95Ms holds the string denoting the probe_ttft_p95_ms field in the database.
	FieldProbeTtftP95Ms = "probe_ttft_p95_ms"
	// FieldProbeSamples holds the string denoting the probe_samples field in the database.
	FieldProbeSamples = "probe_samples"
	// FieldRealTtftP50Ms holds the string denoting the real_ttft_p50_ms field in the database.
	FieldRealTtftP50Ms = "real_ttft_p50_ms"
	// FieldRealTtftAvgMs holds the string denoting the real_ttft_avg_ms field in the database.
	FieldRealTtftAvgMs = "real_ttft_avg_ms"
	// FieldRealTtftP95Ms holds the string denoting the real_ttft_p95_ms field in the database.
	FieldRealTtftP95Ms = "real_ttft_p95_ms"
	// FieldRealTtftSamples holds the string denoting the real_ttft_samples field in the database.
	FieldRealTtftSamples = "real_ttft_samples"
	// FieldRealAvailability6h holds the string denoting the real_availability_6h field in the database.
	FieldRealAvailability6h = "real_availability_6h"
	// FieldRealTotalAvgMs holds the string denoting the real_total_avg_ms field in the database.
	FieldRealTotalAvgMs = "real_total_avg_ms"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the grouphealthstate in the database.
	Table = "group_health_states"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "group_health_states"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
)

// Columns holds all SQL columns for grouphealthstate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldGroupID,
	FieldStatus,
	FieldReason,
	FieldLastProbeAt,
	FieldLastSuccessAt,
	FieldNextProbeAt,
	FieldFailureCount,
	FieldProbeTtftMs,
	FieldProbeAvailability6h,
	FieldProbeTtftAvgMs,
	FieldProbeTtftP95Ms,
	FieldProbeSamples,
	FieldRealTtftP50Ms,
	FieldRealTtftAvgMs,
	FieldRealTtftP95Ms,
	FieldRealTtftSamples,
	FieldRealAvailability6h,
	FieldRealTotalAvgMs,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultFailureCount holds the default value on creation for the "failure_count" field.
	DefaultFailureCount int
	// DefaultProbeTtftMs holds the default value on creation for the "probe_ttft_ms" field.
	DefaultProbeTtftMs int
	// DefaultProbeAvailability6h holds the default value on creation for the "probe_availability_6h" field.
	DefaultProbeAvailability6h float64
	// DefaultProbeTtftAvgMs holds the default value on creation for the "probe_ttft_avg_ms" field.
	DefaultProbeTtftAvgMs int
	// DefaultProbeTtftP95Ms holds the default value on creation for the "probe_ttft_p95_ms" field.
	DefaultProbeTtftP95Ms int
	// DefaultProbeSamples holds the default value on creation for the "probe_samples" field.
	DefaultProbeSamples int
	// DefaultRealTtftP50Ms holds the default value on creation for the "real_ttft_p50_ms" field.
	DefaultRealTtftP50Ms int
	// DefaultRealTtftAvgMs holds the default value on creation for the "real_ttft_avg_ms" field.
	DefaultRealTtftAvgMs int
	// DefaultRealTtftP95Ms holds the default value on creation for the "real_ttft_p95_ms" field.
	DefaultRealTtftP95Ms int
	// DefaultRealTtftSamples holds the default value on creation for the "real_ttft_samples" field.
	DefaultRealTtftSamples int
	// DefaultRealAvailability6h holds the default value on creation for the "real_availability_6h" field.
	DefaultRealAvailability6h float64
	// DefaultRealTotalAvgMs holds the default value on creation for the "real_total_avg_ms" field.
	DefaultRealTotalAvgMs int
)

// OrderOption defines the ordering options for the GroupHealthState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByLastProbeAt orders the results by the last_probe_at field.
func ByLastProbeAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProbeAt, opts...).ToFunc()
}

// ByLastSuccessAt orders the results by the last_success_at field.
func ByLastSuccessAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSuccessAt, opts...).ToFunc()
}

// ByNextProbeAt orders the results by the next_probe_at field.
func ByNextProbeAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextProbeAt, opts...).ToFunc()
}

// ByFailureCount orders the results by the failure_count field.
func ByFailureCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureCount, opts...).ToFunc()
}

// ByProbeTtftMs orders the results by the probe_ttft_ms field.
func ByProbeTtftMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeTtftMs, opts...).ToFunc()
}

// ByProbeAvailability6h orders the results by the probe_availability_6h field.
func ByProbeAvailability6h(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeAvailability6h, opts...).ToFunc()
}

// ByProbeTtftAvgMs orders the results by the probe_ttft_avg_ms field.
func ByProbeTtftAvgMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeTtftAvgMs, opts...).ToFunc()
}

// ByProbeTtftP95Ms orders the results by the probe_ttft_p95_ms field.
func ByProbeTtftP95Ms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeTtftP95Ms, opts...).ToFunc()
}

// ByProbeSamples orders the results by the probe_samples field.
func ByProbeSamples(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeSamples, opts...).ToFunc()
}

// ByRealTtftP50Ms orders the results by the real_ttft_p50_ms field.
func ByRealTtftP50Ms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealTtftP50Ms, opts...).ToFunc()
}

// ByRealTtftAvgMs orders the results by the real_ttft_avg_ms field.
func ByRealTtftAvgMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealTtftAvgMs, opts...).ToFunc()
}

// ByRealTtftP95Ms orders the results by the real_ttft_p95_ms field.
func ByRealTtftP95Ms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealTtftP95Ms, opts...).ToFunc()
}

// ByRealTtftSamples orders the results by the real_ttft_samples field.
func ByRealTtftSamples(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealTtftSamples, opts...).ToFunc()
}

// ByRealAvailability6h orders the results by the real_availability_6h field.
func ByRealAvailability6h(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealAvailability6h, opts...).ToFunc()
}

// ByRealTotalAvgMs orders the results by the real_total_avg_ms field.
func ByRealTotalAvgMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealTotalAvgMs, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
