// Code generated by ent, DO NOT EDIT.

package grouphealthstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldGroupID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldStatus, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldReason, v))
}

// LastProbeAt applies equality check predicate on the "last_probe_at" field. It's identical to LastProbeAtEQ.
func LastProbeAt(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldLastProbeAt, v))
}

// LastSuccessAt applies equality check predicate on the "last_success_at" field. It's identical to LastSuccessAtEQ.
func LastSuccessAt(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldLastSuccessAt, v))
}

// NextProbeAt applies equality check predicate on the "next_probe_at" field. It's identical to NextProbeAtEQ.
func NextProbeAt(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldNextProbeAt, v))
}

// FailureCount applies equality check predicate on the "failure_count" field. It's identical to FailureCountEQ.
func FailureCount(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldFailureCount, v))
}

// ProbeTtftMs applies equality check predicate on the "probe_ttft_ms" field. It's identical to ProbeTtftMsEQ.
func ProbeTtftMs(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldProbeTtftMs, v))
}

// ProbeAvailability6h applies equality check predicate on the "probe_availability_6h" field. It's identical to ProbeAvailability6hEQ.
func ProbeAvailability6h(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldProbeAvailability6h, v))
}

// ProbeTtftAvgMs applies equality check predicate on the "probe_ttft_avg_ms" field. It's identical to ProbeTtftAvgMsEQ.
func ProbeTtftAvgMs(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldProbeTtftAvgMs, v))
}

// ProbeTtftP95Ms applies equality check predicate on the "probe_ttft_p95_ms" field. It's identical to ProbeTtftP95MsEQ.
func ProbeTtftP95Ms(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldProbeTtftP95Ms, v))
}

// ProbeSamples applies equality check predicate on the "probe_samples" field. It's identical to ProbeSamplesEQ.
func ProbeSamples(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldProbeSamples, v))
}

// RealTtftP50Ms applies equality check predicate on the "real_ttft_p50_ms" field. It's identical to RealTtftP50MsEQ.
func RealTtftP50Ms(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldRealTtftP50Ms, v))
}

// RealTtftAvgMs applies equality check predicate on the "real_ttft_avg_ms" field. It's identical to RealTtftAvgMsEQ.
func RealTtftAvgMs(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldRealTtftAvgMs, v))
}

// RealTtftP95Ms applies equality check predicate on the "real_ttft_p95_ms" field. It's identical to RealTtftP95MsEQ.
func RealTtftP95Ms(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldRealTtftP95Ms, v))
}

// RealTtftSamples applies equality check predicate on the "real_ttft_samples" field. It's identical to RealTtftSamplesEQ.
func RealTtftSamples(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldRealTtftSamples, v))
}

// RealAvailability6h applies equality check predicate on the "real_availability_6h" field. It's identical to RealAvailability6hEQ.
func RealAvailability6h(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldRealAvailability6h, v))
}

// RealTotalAvgMs applies equality check predicate on the "real_total_avg_ms" field. It's identical to RealTotalAvgMsEQ.
func RealTotalAvgMs(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldRealTotalAvgMs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldGroupID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldContainsFold(FieldStatus, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldContainsFold(FieldReason, v))
}

// LastProbeAtEQ applies the EQ predicate on the "last_probe_at" field.
func LastProbeAtEQ(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldLastProbeAt, v))
}

// LastProbeAtNEQ applies the NEQ predicate on the "last_probe_at" field.
func LastProbeAtNEQ(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldLastProbeAt, v))
}

// LastProbeAtIn applies the In predicate on the "last_probe_at" field.
func LastProbeAtIn(vs ...time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldLastProbeAt, vs...))
}

// LastProbeAtNotIn applies the NotIn predicate on the "last_probe_at" field.
func LastProbeAtNotIn(vs ...time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldLastProbeAt, vs...))
}

// LastProbeAtGT applies the GT predicate on the "last_probe_at" field.
func LastProbeAtGT(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldLastProbeAt, v))
}

// LastProbeAtGTE applies the GTE predicate on the "last_probe_at" field.
func LastProbeAtGTE(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldLastProbeAt, v))
}

// LastProbeAtLT applies the LT predicate on the "last_probe_at" field.
func LastProbeAtLT(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldLastProbeAt, v))
}

// LastProbeAtLTE applies the LTE predicate on the "last_probe_at" field.
func LastProbeAtLTE(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldLastProbeAt, v))
}

// LastProbeAtIsNil applies the IsNil predicate on the "last_probe_at" field.
func LastProbeAtIsNil() predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIsNull(FieldLastProbeAt))
}

// LastProbeAtNotNil applies the NotNil predicate on the "last_probe_at" field.
func LastProbeAtNotNil() predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotNull(FieldLastProbeAt))
}

// LastSuccessAtEQ applies the EQ predicate on the "last_success_at" field.
func LastSuccessAtEQ(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtNEQ applies the NEQ predicate on the "last_success_at" field.
func LastSuccessAtNEQ(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtIn applies the In predicate on the "last_success_at" field.
func LastSuccessAtIn(vs ...time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtNotIn applies the NotIn predicate on the "last_success_at" field.
func LastSuccessAtNotIn(vs ...time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtGT applies the GT predicate on the "last_success_at" field.
func LastSuccessAtGT(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldLastSuccessAt, v))
}

// LastSuccessAtGTE applies the GTE predicate on the "last_success_at" field.
func LastSuccessAtGTE(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldLastSuccessAt, v))
}

// LastSuccessAtLT applies the LT predicate on the "last_success_at" field.
func LastSuccessAtLT(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldLastSuccessAt, v))
}

// LastSuccessAtLTE applies the LTE predicate on the "last_success_at" field.
func LastSuccessAtLTE(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldLastSuccessAt, v))
}

// LastSuccessAtIsNil applies the IsNil predicate on the "last_success_at" field.
func LastSuccessAtIsNil() predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIsNull(FieldLastSuccessAt))
}

// LastSuccessAtNotNil applies the NotNil predicate on the "last_success_at" field.
func LastSuccessAtNotNil() predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotNull(FieldLastSuccessAt))
}

// NextProbeAtEQ applies the EQ predicate on the "next_probe_at" field.
func NextProbeAtEQ(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldNextProbeAt, v))
}

// NextProbeAtNEQ applies the NEQ predicate on the "next_probe_at" field.
func NextProbeAtNEQ(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldNextProbeAt, v))
}

// NextProbeAtIn applies the In predicate on the "next_probe_at" field.
func NextProbeAtIn(vs ...time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldNextProbeAt, vs...))
}

// NextProbeAtNotIn applies the NotIn predicate on the "next_probe_at" field.
func NextProbeAtNotIn(vs ...time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldNextProbeAt, vs...))
}

// NextProbeAtGT applies the GT predicate on the "next_probe_at" field.
func NextProbeAtGT(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldNextProbeAt, v))
}

// NextProbeAtGTE applies the GTE predicate on the "next_probe_at" field.
func NextProbeAtGTE(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldNextProbeAt, v))
}

// NextProbeAtLT applies the LT predicate on the "next_probe_at" field.
func NextProbeAtLT(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldNextProbeAt, v))
}

// NextProbeAtLTE applies the LTE predicate on the "next_probe_at" field.
func NextProbeAtLTE(v time.Time) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldNextProbeAt, v))
}

// NextProbeAtIsNil applies the IsNil predicate on the "next_probe_at" field.
func NextProbeAtIsNil() predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIsNull(FieldNextProbeAt))
}

// NextProbeAtNotNil applies the NotNil predicate on the "next_probe_at" field.
func NextProbeAtNotNil() predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotNull(FieldNextProbeAt))
}

// FailureCountEQ applies the EQ predicate on the "failure_count" field.
func FailureCountEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldFailureCount, v))
}

// FailureCountNEQ applies the NEQ predicate on the "failure_count" field.
func FailureCountNEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldFailureCount, v))
}

// FailureCountIn applies the In predicate on the "failure_count" field.
func FailureCountIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldFailureCount, vs...))
}

// FailureCountNotIn applies the NotIn predicate on the "failure_count" field.
func FailureCountNotIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldFailureCount, vs...))
}

// FailureCountGT applies the GT predicate on the "failure_count" field.
func FailureCountGT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldFailureCount, v))
}

// FailureCountGTE applies the GTE predicate on the "failure_count" field.
func FailureCountGTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldFailureCount, v))
}

// FailureCountLT applies the LT predicate on the "failure_count" field.
func FailureCountLT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldFailureCount, v))
}

// FailureCountLTE applies the LTE predicate on the "failure_count" field.
func FailureCountLTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldFailureCount, v))
}

// ProbeTtftMsEQ applies the EQ predicate on the "probe_ttft_ms" field.
func ProbeTtftMsEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldProbeTtftMs, v))
}

// ProbeTtftMsNEQ applies the NEQ predicate on the "probe_ttft_ms" field.
func ProbeTtftMsNEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldProbeTtftMs, v))
}

// ProbeTtftMsIn applies the In predicate on the "probe_ttft_ms" field.
func ProbeTtftMsIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldProbeTtftMs, vs...))
}

// ProbeTtftMsNotIn applies the NotIn predicate on the "probe_ttft_ms" field.
func ProbeTtftMsNotIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldProbeTtftMs, vs...))
}

// ProbeTtftMsGT applies the GT predicate on the "probe_ttft_ms" field.
func ProbeTtftMsGT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldProbeTtftMs, v))
}

// ProbeTtftMsGTE applies the GTE predicate on the "probe_ttft_ms" field.
func ProbeTtftMsGTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldProbeTtftMs, v))
}

// ProbeTtftMsLT applies the LT predicate on the "probe_ttft_ms" field.
func ProbeTtftMsLT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldProbeTtftMs, v))
}

// ProbeTtftMsLTE applies the LTE predicate on the "probe_ttft_ms" field.
func ProbeTtftMsLTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldProbeTtftMs, v))
}

// ProbeAvailability6hEQ applies the EQ predicate on the "probe_availability_6h" field.
func ProbeAvailability6hEQ(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldProbeAvailability6h, v))
}

// ProbeAvailability6hNEQ applies the NEQ predicate on the "probe_availability_6h" field.
func ProbeAvailability6hNEQ(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldProbeAvailability6h, v))
}

// ProbeAvailability6hIn applies the In predicate on the "probe_availability_6h" field.
func ProbeAvailability6hIn(vs ...float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldProbeAvailability6h, vs...))
}

// ProbeAvailability6hNotIn applies the NotIn predicate on the "probe_availability_6h" field.
func ProbeAvailability6hNotIn(vs ...float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldProbeAvailability6h, vs...))
}

// ProbeAvailability6hGT applies the GT predicate on the "probe_availability_6h" field.
func ProbeAvailability6hGT(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldProbeAvailability6h, v))
}

// ProbeAvailability6hGTE applies the GTE predicate on the "probe_availability_6h" field.
func ProbeAvailability6hGTE(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldProbeAvailability6h, v))
}

// ProbeAvailability6hLT applies the LT predicate on the "probe_availability_6h" field.
func ProbeAvailability6hLT(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldProbeAvailability6h, v))
}

// ProbeAvailability6hLTE applies the LTE predicate on the "probe_availability_6h" field.
func ProbeAvailability6hLTE(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldProbeAvailability6h, v))
}

// ProbeTtftAvgMsEQ applies the EQ predicate on the "probe_ttft_avg_ms" field.
func ProbeTtftAvgMsEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldProbeTtftAvgMs, v))
}

// ProbeTtftAvgMsNEQ applies the NEQ predicate on the "probe_ttft_avg_ms" field.
func ProbeTtftAvgMsNEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldProbeTtftAvgMs, v))
}

// ProbeTtftAvgMsIn applies the In predicate on the "probe_ttft_avg_ms" field.
func ProbeTtftAvgMsIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldProbeTtftAvgMs, vs...))
}

// ProbeTtftAvgMsNotIn applies the NotIn predicate on the "probe_ttft_avg_ms" field.
func ProbeTtftAvgMsNotIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldProbeTtftAvgMs, vs...))
}

// ProbeTtftAvgMsGT applies the GT predicate on the "probe_ttft_avg_ms" field.
func ProbeTtftAvgMsGT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldProbeTtftAvgMs, v))
}

// ProbeTtftAvgMsGTE applies the GTE predicate on the "probe_ttft_avg_ms" field.
func ProbeTtftAvgMsGTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldProbeTtftAvgMs, v))
}

// ProbeTtftAvgMsLT applies the LT predicate on the "probe_ttft_avg_ms" field.
func ProbeTtftAvgMsLT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldProbeTtftAvgMs, v))
}

// ProbeTtftAvgMsLTE applies the LTE predicate on the "probe_ttft_avg_ms" field.
func ProbeTtftAvgMsLTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldProbeTtftAvgMs, v))
}

// ProbeTtftP95MsEQ applies the EQ predicate on the "probe_ttft_p95_ms" field.
func ProbeTtftP95MsEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldProbeTtftP95Ms, v))
}

// ProbeTtftP95MsNEQ applies the NEQ predicate on the "probe_ttft_p95_ms" field.
func ProbeTtftP95MsNEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldProbeTtftP95Ms, v))
}

// ProbeTtftP95MsIn applies the In predicate on the "probe_ttft_p95_ms" field.
func ProbeTtftP95MsIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldProbeTtftP95Ms, vs...))
}

// ProbeTtftP95MsNotIn applies the NotIn predicate on the "probe_ttft_p95_ms" field.
func ProbeTtftP95MsNotIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldProbeTtftP95Ms, vs...))
}

// ProbeTtftP95MsGT applies the GT predicate on the "probe_ttft_p95_ms" field.
func ProbeTtftP95MsGT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldProbeTtftP95Ms, v))
}

// ProbeTtftP95MsGTE applies the GTE predicate on the "probe_ttft_p95_ms" field.
func ProbeTtftP95MsGTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldProbeTtftP95Ms, v))
}

// ProbeTtftP95MsLT applies the LT predicate on the "probe_ttft_p95_ms" field.
func ProbeTtftP95MsLT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldProbeTtftP95Ms, v))
}

// ProbeTtftP95MsLTE applies the LTE predicate on the "probe_ttft_p95_ms" field.
func ProbeTtftP95MsLTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldProbeTtftP95Ms, v))
}

// ProbeSamplesEQ applies the EQ predicate on the "probe_samples" field.
func ProbeSamplesEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldProbeSamples, v))
}

// ProbeSamplesNEQ applies the NEQ predicate on the "probe_samples" field.
func ProbeSamplesNEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldProbeSamples, v))
}

// ProbeSamplesIn applies the In predicate on the "probe_samples" field.
func ProbeSamplesIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldProbeSamples, vs...))
}

// ProbeSamplesNotIn applies the NotIn predicate on the "probe_samples" field.
func ProbeSamplesNotIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldProbeSamples, vs...))
}

// ProbeSamplesGT applies the GT predicate on the "probe_samples" field.
func ProbeSamplesGT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldProbeSamples, v))
}

// ProbeSamplesGTE applies the GTE predicate on the "probe_samples" field.
func ProbeSamplesGTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldProbeSamples, v))
}

// ProbeSamplesLT applies the LT predicate on the "probe_samples" field.
func ProbeSamplesLT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldProbeSamples, v))
}

// ProbeSamplesLTE applies the LTE predicate on the "probe_samples" field.
func ProbeSamplesLTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldProbeSamples, v))
}

// RealTtftP50MsEQ applies the EQ predicate on the "real_ttft_p50_ms" field.
func RealTtftP50MsEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldRealTtftP50Ms, v))
}

// RealTtftP50MsNEQ applies the NEQ predicate on the "real_ttft_p50_ms" field.
func RealTtftP50MsNEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldRealTtftP50Ms, v))
}

// RealTtftP50MsIn applies the In predicate on the "real_ttft_p50_ms" field.
func RealTtftP50MsIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldRealTtftP50Ms, vs...))
}

// RealTtftP50MsNotIn applies the NotIn predicate on the "real_ttft_p50_ms" field.
func RealTtftP50MsNotIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldRealTtftP50Ms, vs...))
}

// RealTtftP50MsGT applies the GT predicate on the "real_ttft_p50_ms" field.
func RealTtftP50MsGT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldRealTtftP50Ms, v))
}

// RealTtftP50MsGTE applies the GTE predicate on the "real_ttft_p50_ms" field.
func RealTtftP50MsGTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldRealTtftP50Ms, v))
}

// RealTtftP50MsLT applies the LT predicate on the "real_ttft_p50_ms" field.
func RealTtftP50MsLT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldRealTtftP50Ms, v))
}

// RealTtftP50MsLTE applies the LTE predicate on the "real_ttft_p50_ms" field.
func RealTtftP50MsLTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldRealTtftP50Ms, v))
}

// RealTtftAvgMsEQ applies the EQ predicate on the "real_ttft_avg_ms" field.
func RealTtftAvgMsEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldRealTtftAvgMs, v))
}

// RealTtftAvgMsNEQ applies the NEQ predicate on the "real_ttft_avg_ms" field.
func RealTtftAvgMsNEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldRealTtftAvgMs, v))
}

// RealTtftAvgMsIn applies the In predicate on the "real_ttft_avg_ms" field.
func RealTtftAvgMsIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldRealTtftAvgMs, vs...))
}

// RealTtftAvgMsNotIn applies the NotIn predicate on the "real_ttft_avg_ms" field.
func RealTtftAvgMsNotIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldRealTtftAvgMs, vs...))
}

// RealTtftAvgMsGT applies the GT predicate on the "real_ttft_avg_ms" field.
func RealTtftAvgMsGT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldRealTtftAvgMs, v))
}

// RealTtftAvgMsGTE applies the GTE predicate on the "real_ttft_avg_ms" field.
func RealTtftAvgMsGTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldRealTtftAvgMs, v))
}

// RealTtftAvgMsLT applies the LT predicate on the "real_ttft_avg_ms" field.
func RealTtftAvgMsLT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldRealTtftAvgMs, v))
}

// RealTtftAvgMsLTE applies the LTE predicate on the "real_ttft_avg_ms" field.
func RealTtftAvgMsLTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldRealTtftAvgMs, v))
}

// RealTtftP95MsEQ applies the EQ predicate on the "real_ttft_p95_ms" field.
func RealTtftP95MsEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldRealTtftP95Ms, v))
}

// RealTtftP95MsNEQ applies the NEQ predicate on the "real_ttft_p95_ms" field.
func RealTtftP95MsNEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldRealTtftP95Ms, v))
}

// RealTtftP95MsIn applies the In predicate on the "real_ttft_p95_ms" field.
func RealTtftP95MsIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldRealTtftP95Ms, vs...))
}

// RealTtftP95MsNotIn applies the NotIn predicate on the "real_ttft_p95_ms" field.
func RealTtftP95MsNotIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldRealTtftP95Ms, vs...))
}

// RealTtftP95MsGT applies the GT predicate on the "real_ttft_p95_ms" field.
func RealTtftP95MsGT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldRealTtftP95Ms, v))
}

// RealTtftP95MsGTE applies the GTE predicate on the "real_ttft_p95_ms" field.
func RealTtftP95MsGTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldRealTtftP95Ms, v))
}

// RealTtftP95MsLT applies the LT predicate on the "real_ttft_p95_ms" field.
func RealTtftP95MsLT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldRealTtftP95Ms, v))
}

// RealTtftP95MsLTE applies the LTE predicate on the "real_ttft_p95_ms" field.
func RealTtftP95MsLTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldRealTtftP95Ms, v))
}

// RealTtftSamplesEQ applies the EQ predicate on the "real_ttft_samples" field.
func RealTtftSamplesEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldRealTtftSamples, v))
}

// RealTtftSamplesNEQ applies the NEQ predicate on the "real_ttft_samples" field.
func RealTtftSamplesNEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldRealTtftSamples, v))
}

// RealTtftSamplesIn applies the In predicate on the "real_ttft_samples" field.
func RealTtftSamplesIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldRealTtftSamples, vs...))
}

// RealTtftSamplesNotIn applies the NotIn predicate on the "real_ttft_samples" field.
func RealTtftSamplesNotIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldRealTtftSamples, vs...))
}

// RealTtftSamplesGT applies the GT predicate on the "real_ttft_samples" field.
func RealTtftSamplesGT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldRealTtftSamples, v))
}

// RealTtftSamplesGTE applies the GTE predicate on the "real_ttft_samples" field.
func RealTtftSamplesGTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldRealTtftSamples, v))
}

// RealTtftSamplesLT applies the LT predicate on the "real_ttft_samples" field.
func RealTtftSamplesLT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldRealTtftSamples, v))
}

// RealTtftSamplesLTE applies the LTE predicate on the "real_ttft_samples" field.
func RealTtftSamplesLTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldRealTtftSamples, v))
}

// RealAvailability6hEQ applies the EQ predicate on the "real_availability_6h" field.
func RealAvailability6hEQ(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldRealAvailability6h, v))
}

// RealAvailability6hNEQ applies the NEQ predicate on the "real_availability_6h" field.
func RealAvailability6hNEQ(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldRealAvailability6h, v))
}

// RealAvailability6hIn applies the In predicate on the "real_availability_6h" field.
func RealAvailability6hIn(vs ...float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldRealAvailability6h, vs...))
}

// RealAvailability6hNotIn applies the NotIn predicate on the "real_availability_6h" field.
func RealAvailability6hNotIn(vs ...float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldRealAvailability6h, vs...))
}

// RealAvailability6hGT applies the GT predicate on the "real_availability_6h" field.
func RealAvailability6hGT(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldRealAvailability6h, v))
}

// RealAvailability6hGTE applies the GTE predicate on the "real_availability_6h" field.
func RealAvailability6hGTE(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldRealAvailability6h, v))
}

// RealAvailability6hLT applies the LT predicate on the "real_availability_6h" field.
func RealAvailability6hLT(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldRealAvailability6h, v))
}

// RealAvailability6hLTE applies the LTE predicate on the "real_availability_6h" field.
func RealAvailability6hLTE(v float64) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldRealAvailability6h, v))
}

// RealTotalAvgMsEQ applies the EQ predicate on the "real_total_avg_ms" field.
func RealTotalAvgMsEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldEQ(FieldRealTotalAvgMs, v))
}

// RealTotalAvgMsNEQ applies the NEQ predicate on the "real_total_avg_ms" field.
func RealTotalAvgMsNEQ(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNEQ(FieldRealTotalAvgMs, v))
}

// RealTotalAvgMsIn applies the In predicate on the "real_total_avg_ms" field.
func RealTotalAvgMsIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldIn(FieldRealTotalAvgMs, vs...))
}

// RealTotalAvgMsNotIn applies the NotIn predicate on the "real_total_avg_ms" field.
func RealTotalAvgMsNotIn(vs ...int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldNotIn(FieldRealTotalAvgMs, vs...))
}

// RealTotalAvgMsGT applies the GT predicate on the "real_total_avg_ms" field.
func RealTotalAvgMsGT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGT(FieldRealTotalAvgMs, v))
}

// RealTotalAvgMsGTE applies the GTE predicate on the "real_total_avg_ms" field.
func RealTotalAvgMsGTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldGTE(FieldRealTotalAvgMs, v))
}

// RealTotalAvgMsLT applies the LT predicate on the "real_total_avg_ms" field.
func RealTotalAvgMsLT(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLT(FieldRealTotalAvgMs, v))
}

// RealTotalAvgMsLTE applies the LTE predicate on the "real_total_avg_ms" field.
func RealTotalAvgMsLTE(v int) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.FieldLTE(FieldRealTotalAvgMs, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.GroupHealthState {
	return predicate.GroupHealthState(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.GroupHealthState {
	return predicate.GroupHealthState(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupHealthState) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupHealthState) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupHealthState) predicate.GroupHealthState {
	return predicate.GroupHealthState(sql.NotPredicates(p))
}
