// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikeygrouppreference"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// APIKeyGroupPreferenceDelete is the builder for deleting a APIKeyGroupPreference entity.
type APIKeyGroupPreferenceDelete struct {
	config
	hooks    []Hook
	mutation *APIKeyGroupPreferenceMutation
}

// Where appends a list predicates to the APIKeyGroupPreferenceDelete builder.
func (_d *APIKeyGroupPreferenceDelete) Where(ps ...predicate.APIKeyGroupPreference) *APIKeyGroupPreferenceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *APIKeyGroupPreferenceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *APIKeyGroupPreferenceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *APIKeyGroupPreferenceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(apikeygrouppreference.Table, sqlgraph.NewFieldSpec(apikeygrouppreference.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// APIKeyGroupPreferenceDeleteOne is the builder for deleting a single APIKeyGroupPreference entity.
type APIKeyGroupPreferenceDeleteOne struct {
	_d *APIKeyGroupPreferenceDelete
}

// Where appends a list predicates to the APIKeyGroupPreferenceDelete builder.
func (_d *APIKeyGroupPreferenceDeleteOne) Where(ps ...predicate.APIKeyGroupPreference) *APIKeyGroupPreferenceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *APIKeyGroupPreferenceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{apikeygrouppreference.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *APIKeyGroupPreferenceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
