// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeygrouppreference"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// APIKeyGroupPreferenceCreate is the builder for creating a APIKeyGroupPreference entity.
type APIKeyGroupPreferenceCreate struct {
	config
	mutation *APIKeyGroupPreferenceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *APIKeyGroupPreferenceCreate) SetCreatedAt(v time.Time) *APIKeyGroupPreferenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APIKeyGroupPreferenceCreate) SetNillableCreatedAt(v *time.Time) *APIKeyGroupPreferenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *APIKeyGroupPreferenceCreate) SetUpdatedAt(v time.Time) *APIKeyGroupPreferenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *APIKeyGroupPreferenceCreate) SetNillableUpdatedAt(v *time.Time) *APIKeyGroupPreferenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *APIKeyGroupPreferenceCreate) SetAPIKeyID(v int64) *APIKeyGroupPreferenceCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *APIKeyGroupPreferenceCreate) SetGroupID(v int64) *APIKeyGroupPreferenceCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *APIKeyGroupPreferenceCreate) SetDisabled(v bool) *APIKeyGroupPreferenceCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *APIKeyGroupPreferenceCreate) SetNillableDisabled(v *bool) *APIKeyGroupPreferenceCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *APIKeyGroupPreferenceCreate) SetPosition(v int) *APIKeyGroupPreferenceCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *APIKeyGroupPreferenceCreate) SetNillablePosition(v *int) *APIKeyGroupPreferenceCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *APIKeyGroupPreferenceCreate) SetAPIKey(v *APIKey) *APIKeyGroupPreferenceCreate {
	return _c.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *APIKeyGroupPreferenceCreate) SetGroup(v *Group) *APIKeyGroupPreferenceCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the APIKeyGroupPreferenceMutation object of the builder.
func (_c *APIKeyGroupPreferenceCreate) Mutation() *APIKeyGroupPreferenceMutation {
	return _c.mutation
}

// Save creates the APIKeyGroupPreference in the database.
func (_c *APIKeyGroupPreferenceCreate) Save(ctx context.Context) (*APIKeyGroupPreference, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIKeyGroupPreferenceCreate) SaveX(ctx context.Context) *APIKeyGroupPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyGroupPreferenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyGroupPreferenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APIKeyGroupPreferenceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apikeygrouppreference.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apikeygrouppreference.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := apikeygrouppreference.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.Position(); !ok {
		v := apikeygrouppreference.DefaultPosition
		_c.mutation.SetPosition(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIKeyGroupPreferenceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APIKeyGroupPreference.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "APIKeyGroupPreference.updated_at"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "APIKeyGroupPreference.api_key_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "APIKeyGroupPreference.group_id"`)}
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New(`ent: missing required field "APIKeyGroupPreference.disabled"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "APIKeyGroupPreference.position"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "APIKeyGroupPreference.api_key"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "APIKeyGroupPreference.group"`)}
	}
	return nil
}

func (_c *APIKeyGroupPreferenceCreate) sqlSave(ctx context.Context) (*APIKeyGroupPreference, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIKeyGroupPreferenceCreate) createSpec() (*APIKeyGroupPreference, *sqlgraph.CreateSpec) {
	var (
		_node = &APIKeyGroupPreference{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikeygrouppreference.Table, sqlgraph.NewFieldSpec(apikeygrouppreference.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apikeygrouppreference.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeygrouppreference.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(apikeygrouppreference.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(apikeygrouppreference.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygrouppreference.APIKeyTable,
			Columns: []string{apikeygrouppreference.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygrouppreference.GroupTable,
			Columns: []string{apikeygrouppreference.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyGroupPreference.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyGroupPreferenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyGroupPreferenceCreate) OnConflict(opts ...sql.ConflictOption) *APIKeyGroupPreferenceUpsertOne {
	_c.conflict = opts
	return &APIKeyGroupPreferenceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyGroupPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyGroupPreferenceCreate) OnConflictColumns(columns ...string) *APIKeyGroupPreferenceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyGroupPreferenceUpsertOne{
		create: _c,
	}
}

type (
	// APIKeyGroupPreferenceUpsertOne is the builder for "upsert"-ing
	//  one APIKeyGroupPreference node.
	APIKeyGroupPreferenceUpsertOne struct {
		create *APIKeyGroupPreferenceCreate
	}

	// APIKeyGroupPreferenceUpsert is the "OnConflict" setter.
	APIKeyGroupPreferenceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyGroupPreferenceUpsert) SetUpdatedAt(v time.Time) *APIKeyGroupPreferenceUpsert {
	u.Set(apikeygrouppreference.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsert) UpdateUpdatedAt() *APIKeyGroupPreferenceUpsert {
	u.SetExcluded(apikeygrouppreference.FieldUpdatedAt)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyGroupPreferenceUpsert) SetAPIKeyID(v int64) *APIKeyGroupPreferenceUpsert {
	u.Set(apikeygrouppreference.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsert) UpdateAPIKeyID() *APIKeyGroupPreferenceUpsert {
	u.SetExcluded(apikeygrouppreference.FieldAPIKeyID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *APIKeyGroupPreferenceUpsert) SetGroupID(v int64) *APIKeyGroupPreferenceUpsert {
	u.Set(apikeygrouppreference.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsert) UpdateGroupID() *APIKeyGroupPreferenceUpsert {
	u.SetExcluded(apikeygrouppreference.FieldGroupID)
	return u
}

// SetDisabled sets the "disabled" field.
func (u *APIKeyGroupPreferenceUpsert) SetDisabled(v bool) *APIKeyGroupPreferenceUpsert {
	u.Set(apikeygrouppreference.FieldDisabled, v)
	return u
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsert) UpdateDisabled() *APIKeyGroupPreferenceUpsert {
	u.SetExcluded(apikeygrouppreference.FieldDisabled)
	return u
}

// SetPosition sets the "position" field.
func (u *APIKeyGroupPreferenceUpsert) SetPosition(v int) *APIKeyGroupPreferenceUpsert {
	u.Set(apikeygrouppreference.FieldPosition, v)
	return u
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsert) UpdatePosition() *APIKeyGroupPreferenceUpsert {
	u.SetExcluded(apikeygrouppreference.FieldPosition)
	return u
}

// AddPosition adds v to the "position" field.
func (u *APIKeyGroupPreferenceUpsert) AddPosition(v int) *APIKeyGroupPreferenceUpsert {
	u.Add(apikeygrouppreference.FieldPosition, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.APIKeyGroupPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyGroupPreferenceUpsertOne) UpdateNewValues() *APIKeyGroupPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apikeygrouppreference.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyGroupPreference.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APIKeyGroupPreferenceUpsertOne) Ignore() *APIKeyGroupPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyGroupPreferenceUpsertOne) DoNothing() *APIKeyGroupPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyGroupPreferenceCreate.OnConflict
// documentation for more info.
func (u *APIKeyGroupPreferenceUpsertOne) Update(set func(*APIKeyGroupPreferenceUpsert)) *APIKeyGroupPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyGroupPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyGroupPreferenceUpsertOne) SetUpdatedAt(v time.Time) *APIKeyGroupPreferenceUpsertOne {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsertOne) UpdateUpdatedAt() *APIKeyGroupPreferenceUpsertOne {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyGroupPreferenceUpsertOne) SetAPIKeyID(v int64) *APIKeyGroupPreferenceUpsertOne {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsertOne) UpdateAPIKeyID() *APIKeyGroupPreferenceUpsertOne {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *APIKeyGroupPreferenceUpsertOne) SetGroupID(v int64) *APIKeyGroupPreferenceUpsertOne {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsertOne) UpdateGroupID() *APIKeyGroupPreferenceUpsertOne {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.UpdateGroupID()
	})
}

// SetDisabled sets the "disabled" field.
func (u *APIKeyGroupPreferenceUpsertOne) SetDisabled(v bool) *APIKeyGroupPreferenceUpsertOne {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsertOne) UpdateDisabled() *APIKeyGroupPreferenceUpsertOne {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.UpdateDisabled()
	})
}

// SetPosition sets the "position" field.
func (u *APIKeyGroupPreferenceUpsertOne) SetPosition(v int) *APIKeyGroupPreferenceUpsertOne {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.SetPosition(v)
	})
}

// AddPosition adds v to the "position" field.
func (u *APIKeyGroupPreferenceUpsertOne) AddPosition(v int) *APIKeyGroupPreferenceUpsertOne {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.AddPosition(v)
	})
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsertOne) UpdatePosition() *APIKeyGroupPreferenceUpsertOne {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.UpdatePosition()
	})
}

// Exec executes the query.
func (u *APIKeyGroupPreferenceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyGroupPreferenceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyGroupPreferenceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APIKeyGroupPreferenceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APIKeyGroupPreferenceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APIKeyGroupPreferenceCreateBulk is the builder for creating many APIKeyGroupPreference entities in bulk.
type APIKeyGroupPreferenceCreateBulk struct {
	config
	err      error
	builders []*APIKeyGroupPreferenceCreate
	conflict []sql.ConflictOption
}

// Save creates the APIKeyGroupPreference entities in the database.
func (_c *APIKeyGroupPreferenceCreateBulk) Save(ctx context.Context) ([]*APIKeyGroupPreference, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIKeyGroupPreference, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIKeyGroupPreferenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIKeyGroupPreferenceCreateBulk) SaveX(ctx context.Context) []*APIKeyGroupPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyGroupPreferenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyGroupPreferenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyGroupPreference.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyGroupPreferenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyGroupPreferenceCreateBulk) OnConflict(opts ...sql.ConflictOption) *APIKeyGroupPreferenceUpsertBulk {
	_c.conflict = opts
	return &APIKeyGroupPreferenceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyGroupPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyGroupPreferenceCreateBulk) OnConflictColumns(columns ...string) *APIKeyGroupPreferenceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyGroupPreferenceUpsertBulk{
		create: _c,
	}
}

// APIKeyGroupPreferenceUpsertBulk is the builder for "upsert"-ing
// a bulk of APIKeyGroupPreference nodes.
type APIKeyGroupPreferenceUpsertBulk struct {
	create *APIKeyGroupPreferenceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIKeyGroupPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyGroupPreferenceUpsertBulk) UpdateNewValues() *APIKeyGroupPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apikeygrouppreference.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyGroupPreference.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APIKeyGroupPreferenceUpsertBulk) Ignore() *APIKeyGroupPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyGroupPreferenceUpsertBulk) DoNothing() *APIKeyGroupPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyGroupPreferenceCreateBulk.OnConflict
// documentation for more info.
func (u *APIKeyGroupPreferenceUpsertBulk) Update(set func(*APIKeyGroupPreferenceUpsert)) *APIKeyGroupPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyGroupPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyGroupPreferenceUpsertBulk) SetUpdatedAt(v time.Time) *APIKeyGroupPreferenceUpsertBulk {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsertBulk) UpdateUpdatedAt() *APIKeyGroupPreferenceUpsertBulk {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyGroupPreferenceUpsertBulk) SetAPIKeyID(v int64) *APIKeyGroupPreferenceUpsertBulk {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsertBulk) UpdateAPIKeyID() *APIKeyGroupPreferenceUpsertBulk {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *APIKeyGroupPreferenceUpsertBulk) SetGroupID(v int64) *APIKeyGroupPreferenceUpsertBulk {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsertBulk) UpdateGroupID() *APIKeyGroupPreferenceUpsertBulk {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.UpdateGroupID()
	})
}

// SetDisabled sets the "disabled" field.
func (u *APIKeyGroupPreferenceUpsertBulk) SetDisabled(v bool) *APIKeyGroupPreferenceUpsertBulk {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsertBulk) UpdateDisabled() *APIKeyGroupPreferenceUpsertBulk {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.UpdateDisabled()
	})
}

// SetPosition sets the "position" field.
func (u *APIKeyGroupPreferenceUpsertBulk) SetPosition(v int) *APIKeyGroupPreferenceUpsertBulk {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.SetPosition(v)
	})
}

// AddPosition adds v to the "position" field.
func (u *APIKeyGroupPreferenceUpsertBulk) AddPosition(v int) *APIKeyGroupPreferenceUpsertBulk {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.AddPosition(v)
	})
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *APIKeyGroupPreferenceUpsertBulk) UpdatePosition() *APIKeyGroupPreferenceUpsertBulk {
	return u.Update(func(s *APIKeyGroupPreferenceUpsert) {
		s.UpdatePosition()
	})
}

// Exec executes the query.
func (u *APIKeyGroupPreferenceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the APIKeyGroupPreferenceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyGroupPreferenceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyGroupPreferenceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
