// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeygrouppreference"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// APIKeyGroupPreferenceUpdate is the builder for updating APIKeyGroupPreference entities.
type APIKeyGroupPreferenceUpdate struct {
	config
	hooks    []Hook
	mutation *APIKeyGroupPreferenceMutation
}

// Where appends a list predicates to the APIKeyGroupPreferenceUpdate builder.
func (_u *APIKeyGroupPreferenceUpdate) Where(ps ...predicate.APIKeyGroupPreference) *APIKeyGroupPreferenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyGroupPreferenceUpdate) SetUpdatedAt(v time.Time) *APIKeyGroupPreferenceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeyGroupPreferenceUpdate) SetAPIKeyID(v int64) *APIKeyGroupPreferenceUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeyGroupPreferenceUpdate) SetNillableAPIKeyID(v *int64) *APIKeyGroupPreferenceUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *APIKeyGroupPreferenceUpdate) SetGroupID(v int64) *APIKeyGroupPreferenceUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *APIKeyGroupPreferenceUpdate) SetNillableGroupID(v *int64) *APIKeyGroupPreferenceUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *APIKeyGroupPreferenceUpdate) SetDisabled(v bool) *APIKeyGroupPreferenceUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *APIKeyGroupPreferenceUpdate) SetNillableDisabled(v *bool) *APIKeyGroupPreferenceUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *APIKeyGroupPreferenceUpdate) SetPosition(v int) *APIKeyGroupPreferenceUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *APIKeyGroupPreferenceUpdate) SetNillablePosition(v *int) *APIKeyGroupPreferenceUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *APIKeyGroupPreferenceUpdate) AddPosition(v int) *APIKeyGroupPreferenceUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *APIKeyGroupPreferenceUpdate) SetAPIKey(v *APIKey) *APIKeyGroupPreferenceUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *APIKeyGroupPreferenceUpdate) SetGroup(v *Group) *APIKeyGroupPreferenceUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the APIKeyGroupPreferenceMutation object of the builder.
func (_u *APIKeyGroupPreferenceUpdate) Mutation() *APIKeyGroupPreferenceMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *APIKeyGroupPreferenceUpdate) ClearAPIKey() *APIKeyGroupPreferenceUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *APIKeyGroupPreferenceUpdate) ClearGroup() *APIKeyGroupPreferenceUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeyGroupPreferenceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyGroupPreferenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeyGroupPreferenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyGroupPreferenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyGroupPreferenceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeygrouppreference.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyGroupPreferenceUpdate) check() error {
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyGroupPreference.api_key"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyGroupPreference.group"`)
	}
	return nil
}

func (_u *APIKeyGroupPreferenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeygrouppreference.Table, apikeygrouppreference.Columns, sqlgraph.NewFieldSpec(apikeygrouppreference.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeygrouppreference.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(apikeygrouppreference.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(apikeygrouppreference.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(apikeygrouppreference.FieldPosition, field.TypeInt, value)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygrouppreference.APIKeyTable,
			Columns: []string{apikeygrouppreference.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygrouppreference.APIKeyTable,
			Columns: []string{apikeygrouppreference.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygrouppreference.GroupTable,
			Columns: []string{apikeygrouppreference.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygrouppreference.GroupTable,
			Columns: []string{apikeygrouppreference.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeygrouppreference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeyGroupPreferenceUpdateOne is the builder for updating a single APIKeyGroupPreference entity.
type APIKeyGroupPreferenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIKeyGroupPreferenceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyGroupPreferenceUpdateOne) SetUpdatedAt(v time.Time) *APIKeyGroupPreferenceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeyGroupPreferenceUpdateOne) SetAPIKeyID(v int64) *APIKeyGroupPreferenceUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeyGroupPreferenceUpdateOne) SetNillableAPIKeyID(v *int64) *APIKeyGroupPreferenceUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *APIKeyGroupPreferenceUpdateOne) SetGroupID(v int64) *APIKeyGroupPreferenceUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *APIKeyGroupPreferenceUpdateOne) SetNillableGroupID(v *int64) *APIKeyGroupPreferenceUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *APIKeyGroupPreferenceUpdateOne) SetDisabled(v bool) *APIKeyGroupPreferenceUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *APIKeyGroupPreferenceUpdateOne) SetNillableDisabled(v *bool) *APIKeyGroupPreferenceUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *APIKeyGroupPreferenceUpdateOne) SetPosition(v int) *APIKeyGroupPreferenceUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *APIKeyGroupPreferenceUpdateOne) SetNillablePosition(v *int) *APIKeyGroupPreferenceUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *APIKeyGroupPreferenceUpdateOne) AddPosition(v int) *APIKeyGroupPreferenceUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *APIKeyGroupPreferenceUpdateOne) SetAPIKey(v *APIKey) *APIKeyGroupPreferenceUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *APIKeyGroupPreferenceUpdateOne) SetGroup(v *Group) *APIKeyGroupPreferenceUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the APIKeyGroupPreferenceMutation object of the builder.
func (_u *APIKeyGroupPreferenceUpdateOne) Mutation() *APIKeyGroupPreferenceMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *APIKeyGroupPreferenceUpdateOne) ClearAPIKey() *APIKeyGroupPreferenceUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *APIKeyGroupPreferenceUpdateOne) ClearGroup() *APIKeyGroupPreferenceUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the APIKeyGroupPreferenceUpdate builder.
func (_u *APIKeyGroupPreferenceUpdateOne) Where(ps ...predicate.APIKeyGroupPreference) *APIKeyGroupPreferenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeyGroupPreferenceUpdateOne) Select(field string, fields ...string) *APIKeyGroupPreferenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKeyGroupPreference entity.
func (_u *APIKeyGroupPreferenceUpdateOne) Save(ctx context.Context) (*APIKeyGroupPreference, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyGroupPreferenceUpdateOne) SaveX(ctx context.Context) *APIKeyGroupPreference {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeyGroupPreferenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyGroupPreferenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyGroupPreferenceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeygrouppreference.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyGroupPreferenceUpdateOne) check() error {
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyGroupPreference.api_key"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyGroupPreference.group"`)
	}
	return nil
}

func (_u *APIKeyGroupPreferenceUpdateOne) sqlSave(ctx context.Context) (_node *APIKeyGroupPreference, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeygrouppreference.Table, apikeygrouppreference.Columns, sqlgraph.NewFieldSpec(apikeygrouppreference.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKeyGroupPreference.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikeygrouppreference.FieldID)
		for _, f := range fields {
			if !apikeygrouppreference.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikeygrouppreference.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeygrouppreference.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(apikeygrouppreference.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(apikeygrouppreference.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(apikeygrouppreference.FieldPosition, field.TypeInt, value)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygrouppreference.APIKeyTable,
			Columns: []string{apikeygrouppreference.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygrouppreference.APIKeyTable,
			Columns: []string{apikeygrouppreference.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygrouppreference.GroupTable,
			Columns: []string{apikeygrouppreference.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygrouppreference.GroupTable,
			Columns: []string{apikeygrouppreference.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &APIKeyGroupPreference{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeygrouppreference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
