// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grouphealthstate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupHealthStateDelete is the builder for deleting a GroupHealthState entity.
type GroupHealthStateDelete struct {
	config
	hooks    []Hook
	mutation *GroupHealthStateMutation
}

// Where appends a list predicates to the GroupHealthStateDelete builder.
func (_d *GroupHealthStateDelete) Where(ps ...predicate.GroupHealthState) *GroupHealthStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupHealthStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupHealthStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupHealthStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(grouphealthstate.Table, sqlgraph.NewFieldSpec(grouphealthstate.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupHealthStateDeleteOne is the builder for deleting a single GroupHealthState entity.
type GroupHealthStateDeleteOne struct {
	_d *GroupHealthStateDelete
}

// Where appends a list predicates to the GroupHealthStateDelete builder.
func (_d *GroupHealthStateDeleteOne) Where(ps ...predicate.GroupHealthState) *GroupHealthStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupHealthStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{grouphealthstate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupHealthStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
