// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/grouphealthevent"
)

// GroupHealthEventCreate is the builder for creating a GroupHealthEvent entity.
type GroupHealthEventCreate struct {
	config
	mutation *GroupHealthEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupHealthEventCreate) SetCreatedAt(v time.Time) *GroupHealthEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupHealthEventCreate) SetNillableCreatedAt(v *time.Time) *GroupHealthEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupHealthEventCreate) SetUpdatedAt(v time.Time) *GroupHealthEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupHealthEventCreate) SetNillableUpdatedAt(v *time.Time) *GroupHealthEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GroupHealthEventCreate) SetGroupID(v int64) *GroupHealthEventCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *GroupHealthEventCreate) SetAccountID(v int64) *GroupHealthEventCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *GroupHealthEventCreate) SetNillableAccountID(v *int64) *GroupHealthEventCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *GroupHealthEventCreate) SetKind(v string) *GroupHealthEventCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *GroupHealthEventCreate) SetNillableKind(v *string) *GroupHealthEventCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *GroupHealthEventCreate) SetSuccess(v bool) *GroupHealthEventCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_c *GroupHealthEventCreate) SetNillableSuccess(v *bool) *GroupHealthEventCreate {
	if v != nil {
		_c.SetSuccess(*v)
	}
	return _c
}

// SetIsProbe sets the "is_probe" field.
func (_c *GroupHealthEventCreate) SetIsProbe(v bool) *GroupHealthEventCreate {
	_c.mutation.SetIsProbe(v)
	return _c
}

// SetNillableIsProbe sets the "is_probe" field if the given value is not nil.
func (_c *GroupHealthEventCreate) SetNillableIsProbe(v *bool) *GroupHealthEventCreate {
	if v != nil {
		_c.SetIsProbe(*v)
	}
	return _c
}

// SetSemanticStarted sets the "semantic_started" field.
func (_c *GroupHealthEventCreate) SetSemanticStarted(v bool) *GroupHealthEventCreate {
	_c.mutation.SetSemanticStarted(v)
	return _c
}

// SetNillableSemanticStarted sets the "semantic_started" field if the given value is not nil.
func (_c *GroupHealthEventCreate) SetNillableSemanticStarted(v *bool) *GroupHealthEventCreate {
	if v != nil {
		_c.SetSemanticStarted(*v)
	}
	return _c
}

// SetErrorCategory sets the "error_category" field.
func (_c *GroupHealthEventCreate) SetErrorCategory(v string) *GroupHealthEventCreate {
	_c.mutation.SetErrorCategory(v)
	return _c
}

// SetNillableErrorCategory sets the "error_category" field if the given value is not nil.
func (_c *GroupHealthEventCreate) SetNillableErrorCategory(v *string) *GroupHealthEventCreate {
	if v != nil {
		_c.SetErrorCategory(*v)
	}
	return _c
}

// SetTtftMs sets the "ttft_ms" field.
func (_c *GroupHealthEventCreate) SetTtftMs(v int) *GroupHealthEventCreate {
	_c.mutation.SetTtftMs(v)
	return _c
}

// SetNillableTtftMs sets the "ttft_ms" field if the given value is not nil.
func (_c *GroupHealthEventCreate) SetNillableTtftMs(v *int) *GroupHealthEventCreate {
	if v != nil {
		_c.SetTtftMs(*v)
	}
	return _c
}

// SetTotalMs sets the "total_ms" field.
func (_c *GroupHealthEventCreate) SetTotalMs(v int) *GroupHealthEventCreate {
	_c.mutation.SetTotalMs(v)
	return _c
}

// SetNillableTotalMs sets the "total_ms" field if the given value is not nil.
func (_c *GroupHealthEventCreate) SetNillableTotalMs(v *int) *GroupHealthEventCreate {
	if v != nil {
		_c.SetTotalMs(*v)
	}
	return _c
}

// SetObservedAt sets the "observed_at" field.
func (_c *GroupHealthEventCreate) SetObservedAt(v time.Time) *GroupHealthEventCreate {
	_c.mutation.SetObservedAt(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *GroupHealthEventCreate) SetErrorMessage(v string) *GroupHealthEventCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *GroupHealthEventCreate) SetNillableErrorMessage(v *string) *GroupHealthEventCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupHealthEventCreate) SetGroup(v *Group) *GroupHealthEventCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the GroupHealthEventMutation object of the builder.
func (_c *GroupHealthEventCreate) Mutation() *GroupHealthEventMutation {
	return _c.mutation
}

// Save creates the GroupHealthEvent in the database.
func (_c *GroupHealthEventCreate) Save(ctx context.Context) (*GroupHealthEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupHealthEventCreate) SaveX(ctx context.Context) *GroupHealthEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupHealthEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupHealthEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupHealthEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := grouphealthevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := grouphealthevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := grouphealthevent.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.Success(); !ok {
		v := grouphealthevent.DefaultSuccess
		_c.mutation.SetSuccess(v)
	}
	if _, ok := _c.mutation.IsProbe(); !ok {
		v := grouphealthevent.DefaultIsProbe
		_c.mutation.SetIsProbe(v)
	}
	if _, ok := _c.mutation.SemanticStarted(); !ok {
		v := grouphealthevent.DefaultSemanticStarted
		_c.mutation.SetSemanticStarted(v)
	}
	if _, ok := _c.mutation.TtftMs(); !ok {
		v := grouphealthevent.DefaultTtftMs
		_c.mutation.SetTtftMs(v)
	}
	if _, ok := _c.mutation.TotalMs(); !ok {
		v := grouphealthevent.DefaultTotalMs
		_c.mutation.SetTotalMs(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupHealthEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupHealthEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GroupHealthEvent.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupHealthEvent.group_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "GroupHealthEvent.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := grouphealthevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "GroupHealthEvent.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "GroupHealthEvent.success"`)}
	}
	if _, ok := _c.mutation.IsProbe(); !ok {
		return &ValidationError{Name: "is_probe", err: errors.New(`ent: missing required field "GroupHealthEvent.is_probe"`)}
	}
	if _, ok := _c.mutation.SemanticStarted(); !ok {
		return &ValidationError{Name: "semantic_started", err: errors.New(`ent: missing required field "GroupHealthEvent.semantic_started"`)}
	}
	if v, ok := _c.mutation.ErrorCategory(); ok {
		if err := grouphealthevent.ErrorCategoryValidator(v); err != nil {
			return &ValidationError{Name: "error_category", err: fmt.Errorf(`ent: validator failed for field "GroupHealthEvent.error_category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TtftMs(); !ok {
		return &ValidationError{Name: "ttft_ms", err: errors.New(`ent: missing required field "GroupHealthEvent.ttft_ms"`)}
	}
	if _, ok := _c.mutation.TotalMs(); !ok {
		return &ValidationError{Name: "total_ms", err: errors.New(`ent: missing required field "GroupHealthEvent.total_ms"`)}
	}
	if _, ok := _c.mutation.ObservedAt(); !ok {
		return &ValidationError{Name: "observed_at", err: errors.New(`ent: missing required field "GroupHealthEvent.observed_at"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupHealthEvent.group"`)}
	}
	return nil
}

func (_c *GroupHealthEventCreate) sqlSave(ctx context.Context) (*GroupHealthEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupHealthEventCreate) createSpec() (*GroupHealthEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupHealthEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(grouphealthevent.Table, sqlgraph.NewFieldSpec(grouphealthevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(grouphealthevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(grouphealthevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(grouphealthevent.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(grouphealthevent.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(grouphealthevent.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.IsProbe(); ok {
		_spec.SetField(grouphealthevent.FieldIsProbe, field.TypeBool, value)
		_node.IsProbe = value
	}
	if value, ok := _c.mutation.SemanticStarted(); ok {
		_spec.SetField(grouphealthevent.FieldSemanticStarted, field.TypeBool, value)
		_node.SemanticStarted = value
	}
	if value, ok := _c.mutation.ErrorCategory(); ok {
		_spec.SetField(grouphealthevent.FieldErrorCategory, field.TypeString, value)
		_node.ErrorCategory = &value
	}
	if value, ok := _c.mutation.TtftMs(); ok {
		_spec.SetField(grouphealthevent.FieldTtftMs, field.TypeInt, value)
		_node.TtftMs = value
	}
	if value, ok := _c.mutation.TotalMs(); ok {
		_spec.SetField(grouphealthevent.FieldTotalMs, field.TypeInt, value)
		_node.TotalMs = value
	}
	if value, ok := _c.mutation.ObservedAt(); ok {
		_spec.SetField(grouphealthevent.FieldObservedAt, field.TypeTime, value)
		_node.ObservedAt = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(grouphealthevent.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grouphealthevent.GroupTable,
			Columns: []string{grouphealthevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupHealthEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupHealthEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupHealthEventCreate) OnConflict(opts ...sql.ConflictOption) *GroupHealthEventUpsertOne {
	_c.conflict = opts
	return &GroupHealthEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupHealthEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupHealthEventCreate) OnConflictColumns(columns ...string) *GroupHealthEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupHealthEventUpsertOne{
		create: _c,
	}
}

type (
	// GroupHealthEventUpsertOne is the builder for "upsert"-ing
	//  one GroupHealthEvent node.
	GroupHealthEventUpsertOne struct {
		create *GroupHealthEventCreate
	}

	// GroupHealthEventUpsert is the "OnConflict" setter.
	GroupHealthEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupHealthEventUpsert) SetUpdatedAt(v time.Time) *GroupHealthEventUpsert {
	u.Set(grouphealthevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupHealthEventUpsert) UpdateUpdatedAt() *GroupHealthEventUpsert {
	u.SetExcluded(grouphealthevent.FieldUpdatedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupHealthEventUpsert) SetGroupID(v int64) *GroupHealthEventUpsert {
	u.Set(grouphealthevent.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupHealthEventUpsert) UpdateGroupID() *GroupHealthEventUpsert {
	u.SetExcluded(grouphealthevent.FieldGroupID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *GroupHealthEventUpsert) SetAccountID(v int64) *GroupHealthEventUpsert {
	u.Set(grouphealthevent.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *GroupHealthEventUpsert) UpdateAccountID() *GroupHealthEventUpsert {
	u.SetExcluded(grouphealthevent.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *GroupHealthEventUpsert) AddAccountID(v int64) *GroupHealthEventUpsert {
	u.Add(grouphealthevent.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *GroupHealthEventUpsert) ClearAccountID() *GroupHealthEventUpsert {
	u.SetNull(grouphealthevent.FieldAccountID)
	return u
}

// SetKind sets the "kind" field.
func (u *GroupHealthEventUpsert) SetKind(v string) *GroupHealthEventUpsert {
	u.Set(grouphealthevent.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *GroupHealthEventUpsert) UpdateKind() *GroupHealthEventUpsert {
	u.SetExcluded(grouphealthevent.FieldKind)
	return u
}

// SetSuccess sets the "success" field.
func (u *GroupHealthEventUpsert) SetSuccess(v bool) *GroupHealthEventUpsert {
	u.Set(grouphealthevent.FieldSuccess, v)
	return u
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *GroupHealthEventUpsert) UpdateSuccess() *GroupHealthEventUpsert {
	u.SetExcluded(grouphealthevent.FieldSuccess)
	return u
}

// SetIsProbe sets the "is_probe" field.
func (u *GroupHealthEventUpsert) SetIsProbe(v bool) *GroupHealthEventUpsert {
	u.Set(grouphealthevent.FieldIsProbe, v)
	return u
}

// UpdateIsProbe sets the "is_probe" field to the value that was provided on create.
func (u *GroupHealthEventUpsert) UpdateIsProbe() *GroupHealthEventUpsert {
	u.SetExcluded(grouphealthevent.FieldIsProbe)
	return u
}

// SetSemanticStarted sets the "semantic_started" field.
func (u *GroupHealthEventUpsert) SetSemanticStarted(v bool) *GroupHealthEventUpsert {
	u.Set(grouphealthevent.FieldSemanticStarted, v)
	return u
}

// UpdateSemanticStarted sets the "semantic_started" field to the value that was provided on create.
func (u *GroupHealthEventUpsert) UpdateSemanticStarted() *GroupHealthEventUpsert {
	u.SetExcluded(grouphealthevent.FieldSemanticStarted)
	return u
}

// SetErrorCategory sets the "error_category" field.
func (u *GroupHealthEventUpsert) SetErrorCategory(v string) *GroupHealthEventUpsert {
	u.Set(grouphealthevent.FieldErrorCategory, v)
	return u
}

// UpdateErrorCategory sets the "error_category" field to the value that was provided on create.
func (u *GroupHealthEventUpsert) UpdateErrorCategory() *GroupHealthEventUpsert {
	u.SetExcluded(grouphealthevent.FieldErrorCategory)
	return u
}

// ClearErrorCategory clears the value of the "error_category" field.
func (u *GroupHealthEventUpsert) ClearErrorCategory() *GroupHealthEventUpsert {
	u.SetNull(grouphealthevent.FieldErrorCategory)
	return u
}

// SetTtftMs sets the "ttft_ms" field.
func (u *GroupHealthEventUpsert) SetTtftMs(v int) *GroupHealthEventUpsert {
	u.Set(grouphealthevent.FieldTtftMs, v)
	return u
}

// UpdateTtftMs sets the "ttft_ms" field to the value that was provided on create.
func (u *GroupHealthEventUpsert) UpdateTtftMs() *GroupHealthEventUpsert {
	u.SetExcluded(grouphealthevent.FieldTtftMs)
	return u
}

// AddTtftMs adds v to the "ttft_ms" field.
func (u *GroupHealthEventUpsert) AddTtftMs(v int) *GroupHealthEventUpsert {
	u.Add(grouphealthevent.FieldTtftMs, v)
	return u
}

// SetTotalMs sets the "total_ms" field.
func (u *GroupHealthEventUpsert) SetTotalMs(v int) *GroupHealthEventUpsert {
	u.Set(grouphealthevent.FieldTotalMs, v)
	return u
}

// UpdateTotalMs sets the "total_ms" field to the value that was provided on create.
func (u *GroupHealthEventUpsert) UpdateTotalMs() *GroupHealthEventUpsert {
	u.SetExcluded(grouphealthevent.FieldTotalMs)
	return u
}

// AddTotalMs adds v to the "total_ms" field.
func (u *GroupHealthEventUpsert) AddTotalMs(v int) *GroupHealthEventUpsert {
	u.Add(grouphealthevent.FieldTotalMs, v)
	return u
}

// SetObservedAt sets the "observed_at" field.
func (u *GroupHealthEventUpsert) SetObservedAt(v time.Time) *GroupHealthEventUpsert {
	u.Set(grouphealthevent.FieldObservedAt, v)
	return u
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *GroupHealthEventUpsert) UpdateObservedAt() *GroupHealthEventUpsert {
	u.SetExcluded(grouphealthevent.FieldObservedAt)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *GroupHealthEventUpsert) SetErrorMessage(v string) *GroupHealthEventUpsert {
	u.Set(grouphealthevent.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *GroupHealthEventUpsert) UpdateErrorMessage() *GroupHealthEventUpsert {
	u.SetExcluded(grouphealthevent.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *GroupHealthEventUpsert) ClearErrorMessage() *GroupHealthEventUpsert {
	u.SetNull(grouphealthevent.FieldErrorMessage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupHealthEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupHealthEventUpsertOne) UpdateNewValues() *GroupHealthEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(grouphealthevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupHealthEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupHealthEventUpsertOne) Ignore() *GroupHealthEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupHealthEventUpsertOne) DoNothing() *GroupHealthEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupHealthEventCreate.OnConflict
// documentation for more info.
func (u *GroupHealthEventUpsertOne) Update(set func(*GroupHealthEventUpsert)) *GroupHealthEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupHealthEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupHealthEventUpsertOne) SetUpdatedAt(v time.Time) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupHealthEventUpsertOne) UpdateUpdatedAt() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupHealthEventUpsertOne) SetGroupID(v int64) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupHealthEventUpsertOne) UpdateGroupID() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *GroupHealthEventUpsertOne) SetAccountID(v int64) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *GroupHealthEventUpsertOne) AddAccountID(v int64) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *GroupHealthEventUpsertOne) UpdateAccountID() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *GroupHealthEventUpsertOne) ClearAccountID() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.ClearAccountID()
	})
}

// SetKind sets the "kind" field.
func (u *GroupHealthEventUpsertOne) SetKind(v string) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *GroupHealthEventUpsertOne) UpdateKind() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateKind()
	})
}

// SetSuccess sets the "success" field.
func (u *GroupHealthEventUpsertOne) SetSuccess(v bool) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetSuccess(v)
	})
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *GroupHealthEventUpsertOne) UpdateSuccess() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateSuccess()
	})
}

// SetIsProbe sets the "is_probe" field.
func (u *GroupHealthEventUpsertOne) SetIsProbe(v bool) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetIsProbe(v)
	})
}

// UpdateIsProbe sets the "is_probe" field to the value that was provided on create.
func (u *GroupHealthEventUpsertOne) UpdateIsProbe() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateIsProbe()
	})
}

// SetSemanticStarted sets the "semantic_started" field.
func (u *GroupHealthEventUpsertOne) SetSemanticStarted(v bool) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetSemanticStarted(v)
	})
}

// UpdateSemanticStarted sets the "semantic_started" field to the value that was provided on create.
func (u *GroupHealthEventUpsertOne) UpdateSemanticStarted() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateSemanticStarted()
	})
}

// SetErrorCategory sets the "error_category" field.
func (u *GroupHealthEventUpsertOne) SetErrorCategory(v string) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetErrorCategory(v)
	})
}

// UpdateErrorCategory sets the "error_category" field to the value that was provided on create.
func (u *GroupHealthEventUpsertOne) UpdateErrorCategory() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateErrorCategory()
	})
}

// ClearErrorCategory clears the value of the "error_category" field.
func (u *GroupHealthEventUpsertOne) ClearErrorCategory() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.ClearErrorCategory()
	})
}

// SetTtftMs sets the "ttft_ms" field.
func (u *GroupHealthEventUpsertOne) SetTtftMs(v int) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetTtftMs(v)
	})
}

// AddTtftMs adds v to the "ttft_ms" field.
func (u *GroupHealthEventUpsertOne) AddTtftMs(v int) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.AddTtftMs(v)
	})
}

// UpdateTtftMs sets the "ttft_ms" field to the value that was provided on create.
func (u *GroupHealthEventUpsertOne) UpdateTtftMs() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateTtftMs()
	})
}

// SetTotalMs sets the "total_ms" field.
func (u *GroupHealthEventUpsertOne) SetTotalMs(v int) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetTotalMs(v)
	})
}

// AddTotalMs adds v to the "total_ms" field.
func (u *GroupHealthEventUpsertOne) AddTotalMs(v int) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.AddTotalMs(v)
	})
}

// UpdateTotalMs sets the "total_ms" field to the value that was provided on create.
func (u *GroupHealthEventUpsertOne) UpdateTotalMs() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateTotalMs()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *GroupHealthEventUpsertOne) SetObservedAt(v time.Time) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *GroupHealthEventUpsertOne) UpdateObservedAt() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateObservedAt()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *GroupHealthEventUpsertOne) SetErrorMessage(v string) *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *GroupHealthEventUpsertOne) UpdateErrorMessage() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *GroupHealthEventUpsertOne) ClearErrorMessage() *GroupHealthEventUpsertOne {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.ClearErrorMessage()
	})
}

// Exec executes the query.
func (u *GroupHealthEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupHealthEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupHealthEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupHealthEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupHealthEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupHealthEventCreateBulk is the builder for creating many GroupHealthEvent entities in bulk.
type GroupHealthEventCreateBulk struct {
	config
	err      error
	builders []*GroupHealthEventCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupHealthEvent entities in the database.
func (_c *GroupHealthEventCreateBulk) Save(ctx context.Context) ([]*GroupHealthEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupHealthEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupHealthEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupHealthEventCreateBulk) SaveX(ctx context.Context) []*GroupHealthEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupHealthEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupHealthEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupHealthEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupHealthEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupHealthEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupHealthEventUpsertBulk {
	_c.conflict = opts
	return &GroupHealthEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupHealthEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupHealthEventCreateBulk) OnConflictColumns(columns ...string) *GroupHealthEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupHealthEventUpsertBulk{
		create: _c,
	}
}

// GroupHealthEventUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupHealthEvent nodes.
type GroupHealthEventUpsertBulk struct {
	create *GroupHealthEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupHealthEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupHealthEventUpsertBulk) UpdateNewValues() *GroupHealthEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(grouphealthevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupHealthEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupHealthEventUpsertBulk) Ignore() *GroupHealthEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupHealthEventUpsertBulk) DoNothing() *GroupHealthEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupHealthEventCreateBulk.OnConflict
// documentation for more info.
func (u *GroupHealthEventUpsertBulk) Update(set func(*GroupHealthEventUpsert)) *GroupHealthEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupHealthEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupHealthEventUpsertBulk) SetUpdatedAt(v time.Time) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupHealthEventUpsertBulk) UpdateUpdatedAt() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupHealthEventUpsertBulk) SetGroupID(v int64) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupHealthEventUpsertBulk) UpdateGroupID() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *GroupHealthEventUpsertBulk) SetAccountID(v int64) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *GroupHealthEventUpsertBulk) AddAccountID(v int64) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *GroupHealthEventUpsertBulk) UpdateAccountID() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *GroupHealthEventUpsertBulk) ClearAccountID() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.ClearAccountID()
	})
}

// SetKind sets the "kind" field.
func (u *GroupHealthEventUpsertBulk) SetKind(v string) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *GroupHealthEventUpsertBulk) UpdateKind() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateKind()
	})
}

// SetSuccess sets the "success" field.
func (u *GroupHealthEventUpsertBulk) SetSuccess(v bool) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetSuccess(v)
	})
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *GroupHealthEventUpsertBulk) UpdateSuccess() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateSuccess()
	})
}

// SetIsProbe sets the "is_probe" field.
func (u *GroupHealthEventUpsertBulk) SetIsProbe(v bool) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetIsProbe(v)
	})
}

// UpdateIsProbe sets the "is_probe" field to the value that was provided on create.
func (u *GroupHealthEventUpsertBulk) UpdateIsProbe() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateIsProbe()
	})
}

// SetSemanticStarted sets the "semantic_started" field.
func (u *GroupHealthEventUpsertBulk) SetSemanticStarted(v bool) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetSemanticStarted(v)
	})
}

// UpdateSemanticStarted sets the "semantic_started" field to the value that was provided on create.
func (u *GroupHealthEventUpsertBulk) UpdateSemanticStarted() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateSemanticStarted()
	})
}

// SetErrorCategory sets the "error_category" field.
func (u *GroupHealthEventUpsertBulk) SetErrorCategory(v string) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetErrorCategory(v)
	})
}

// UpdateErrorCategory sets the "error_category" field to the value that was provided on create.
func (u *GroupHealthEventUpsertBulk) UpdateErrorCategory() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateErrorCategory()
	})
}

// ClearErrorCategory clears the value of the "error_category" field.
func (u *GroupHealthEventUpsertBulk) ClearErrorCategory() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.ClearErrorCategory()
	})
}

// SetTtftMs sets the "ttft_ms" field.
func (u *GroupHealthEventUpsertBulk) SetTtftMs(v int) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetTtftMs(v)
	})
}

// AddTtftMs adds v to the "ttft_ms" field.
func (u *GroupHealthEventUpsertBulk) AddTtftMs(v int) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.AddTtftMs(v)
	})
}

// UpdateTtftMs sets the "ttft_ms" field to the value that was provided on create.
func (u *GroupHealthEventUpsertBulk) UpdateTtftMs() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateTtftMs()
	})
}

// SetTotalMs sets the "total_ms" field.
func (u *GroupHealthEventUpsertBulk) SetTotalMs(v int) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetTotalMs(v)
	})
}

// AddTotalMs adds v to the "total_ms" field.
func (u *GroupHealthEventUpsertBulk) AddTotalMs(v int) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.AddTotalMs(v)
	})
}

// UpdateTotalMs sets the "total_ms" field to the value that was provided on create.
func (u *GroupHealthEventUpsertBulk) UpdateTotalMs() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateTotalMs()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *GroupHealthEventUpsertBulk) SetObservedAt(v time.Time) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *GroupHealthEventUpsertBulk) UpdateObservedAt() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateObservedAt()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *GroupHealthEventUpsertBulk) SetErrorMessage(v string) *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *GroupHealthEventUpsertBulk) UpdateErrorMessage() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *GroupHealthEventUpsertBulk) ClearErrorMessage() *GroupHealthEventUpsertBulk {
	return u.Update(func(s *GroupHealthEventUpsert) {
		s.ClearErrorMessage()
	})
}

// Exec executes the query.
func (u *GroupHealthEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupHealthEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupHealthEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupHealthEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
