// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/grouphealthevent"
)

// GroupHealthEvent is the model entity for the GroupHealthEvent schema.
type GroupHealthEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Success holds the value of the "success" field.
	Success bool `json:"success,omitempty"`
	// IsProbe holds the value of the "is_probe" field.
	IsProbe bool `json:"is_probe,omitempty"`
	// SemanticStarted holds the value of the "semantic_started" field.
	SemanticStarted bool `json:"semantic_started,omitempty"`
	// ErrorCategory holds the value of the "error_category" field.
	ErrorCategory *string `json:"error_category,omitempty"`
	// TtftMs holds the value of the "ttft_ms" field.
	TtftMs int `json:"ttft_ms,omitempty"`
	// TotalMs holds the value of the "total_ms" field.
	TotalMs int `json:"total_ms,omitempty"`
	// ObservedAt holds the value of the "observed_at" field.
	ObservedAt time.Time `json:"observed_at,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupHealthEventQuery when eager-loading is set.
	Edges        GroupHealthEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupHealthEventEdges holds the relations/edges for other nodes in the graph.
type GroupHealthEventEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupHealthEventEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupHealthEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case grouphealthevent.FieldSuccess, grouphealthevent.FieldIsProbe, grouphealthevent.FieldSemanticStarted:
			values[i] = new(sql.NullBool)
		case grouphealthevent.FieldID, grouphealthevent.FieldGroupID, grouphealthevent.FieldAccountID, grouphealthevent.FieldTtftMs, grouphealthevent.FieldTotalMs:
			values[i] = new(sql.NullInt64)
		case grouphealthevent.FieldKind, grouphealthevent.FieldErrorCategory, grouphealthevent.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case grouphealthevent.FieldCreatedAt, grouphealthevent.FieldUpdatedAt, grouphealthevent.FieldObservedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupHealthEvent fields.
func (_m *GroupHealthEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case grouphealthevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case grouphealthevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case grouphealthevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case grouphealthevent.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case grouphealthevent.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case grouphealthevent.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case grouphealthevent.FieldSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field success", values[i])
			} else if value.Valid {
				_m.Success = value.Bool
			}
		case grouphealthevent.FieldIsProbe:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_probe", values[i])
			} else if value.Valid {
				_m.IsProbe = value.Bool
			}
		case grouphealthevent.FieldSemanticStarted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field semantic_started", values[i])
			} else if value.Valid {
				_m.SemanticStarted = value.Bool
			}
		case grouphealthevent.FieldErrorCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_category", values[i])
			} else if value.Valid {
				_m.ErrorCategory = new(string)
				*_m.ErrorCategory = value.String
			}
		case grouphealthevent.FieldTtftMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ttft_ms", values[i])
			} else if value.Valid {
				_m.TtftMs = int(value.Int64)
			}
		case grouphealthevent.FieldTotalMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_ms", values[i])
			} else if value.Valid {
				_m.TotalMs = int(value.Int64)
			}
		case grouphealthevent.FieldObservedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field observed_at", values[i])
			} else if value.Valid {
				_m.ObservedAt = value.Time
			}
		case grouphealthevent.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupHealthEvent.
// This includes values selected through modifiers, order, etc.
func (_m *GroupHealthEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the GroupHealthEvent entity.
func (_m *GroupHealthEvent) QueryGroup() *GroupQuery {
	return NewGroupHealthEventClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this GroupHealthEvent.
// Note that you need to call GroupHealthEvent.Unwrap() before calling this method if this GroupHealthEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupHealthEvent) Update() *GroupHealthEventUpdateOne {
	return NewGroupHealthEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupHealthEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupHealthEvent) Unwrap() *GroupHealthEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupHealthEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupHealthEvent) String() string {
	var builder strings.Builder
	builder.WriteString("GroupHealthEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("success=")
	builder.WriteString(fmt.Sprintf("%v", _m.Success))
	builder.WriteString(", ")
	builder.WriteString("is_probe=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsProbe))
	builder.WriteString(", ")
	builder.WriteString("semantic_started=")
	builder.WriteString(fmt.Sprintf("%v", _m.SemanticStarted))
	builder.WriteString(", ")
	if v := _m.ErrorCategory; v != nil {
		builder.WriteString("error_category=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("ttft_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.TtftMs))
	builder.WriteString(", ")
	builder.WriteString("total_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalMs))
	builder.WriteString(", ")
	builder.WriteString("observed_at=")
	builder.WriteString(_m.ObservedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// GroupHealthEvents is a parsable slice of GroupHealthEvent.
type GroupHealthEvents []*GroupHealthEvent
