// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/grouphealthstate"
)

// GroupHealthStateCreate is the builder for creating a GroupHealthState entity.
type GroupHealthStateCreate struct {
	config
	mutation *GroupHealthStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupHealthStateCreate) SetCreatedAt(v time.Time) *GroupHealthStateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableCreatedAt(v *time.Time) *GroupHealthStateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupHealthStateCreate) SetUpdatedAt(v time.Time) *GroupHealthStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableUpdatedAt(v *time.Time) *GroupHealthStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GroupHealthStateCreate) SetGroupID(v int64) *GroupHealthStateCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *GroupHealthStateCreate) SetStatus(v string) *GroupHealthStateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableStatus(v *string) *GroupHealthStateCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *GroupHealthStateCreate) SetReason(v string) *GroupHealthStateCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableReason(v *string) *GroupHealthStateCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetLastProbeAt sets the "last_probe_at" field.
func (_c *GroupHealthStateCreate) SetLastProbeAt(v time.Time) *GroupHealthStateCreate {
	_c.mutation.SetLastProbeAt(v)
	return _c
}

// SetNillableLastProbeAt sets the "last_probe_at" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableLastProbeAt(v *time.Time) *GroupHealthStateCreate {
	if v != nil {
		_c.SetLastProbeAt(*v)
	}
	return _c
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_c *GroupHealthStateCreate) SetLastSuccessAt(v time.Time) *GroupHealthStateCreate {
	_c.mutation.SetLastSuccessAt(v)
	return _c
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableLastSuccessAt(v *time.Time) *GroupHealthStateCreate {
	if v != nil {
		_c.SetLastSuccessAt(*v)
	}
	return _c
}

// SetNextProbeAt sets the "next_probe_at" field.
func (_c *GroupHealthStateCreate) SetNextProbeAt(v time.Time) *GroupHealthStateCreate {
	_c.mutation.SetNextProbeAt(v)
	return _c
}

// SetNillableNextProbeAt sets the "next_probe_at" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableNextProbeAt(v *time.Time) *GroupHealthStateCreate {
	if v != nil {
		_c.SetNextProbeAt(*v)
	}
	return _c
}

// SetFailureCount sets the "failure_count" field.
func (_c *GroupHealthStateCreate) SetFailureCount(v int) *GroupHealthStateCreate {
	_c.mutation.SetFailureCount(v)
	return _c
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableFailureCount(v *int) *GroupHealthStateCreate {
	if v != nil {
		_c.SetFailureCount(*v)
	}
	return _c
}

// SetProbeTtftMs sets the "probe_ttft_ms" field.
func (_c *GroupHealthStateCreate) SetProbeTtftMs(v int) *GroupHealthStateCreate {
	_c.mutation.SetProbeTtftMs(v)
	return _c
}

// SetNillableProbeTtftMs sets the "probe_ttft_ms" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableProbeTtftMs(v *int) *GroupHealthStateCreate {
	if v != nil {
		_c.SetProbeTtftMs(*v)
	}
	return _c
}

// SetProbeAvailability6h sets the "probe_availability_6h" field.
func (_c *GroupHealthStateCreate) SetProbeAvailability6h(v float64) *GroupHealthStateCreate {
	_c.mutation.SetProbeAvailability6h(v)
	return _c
}

// SetNillableProbeAvailability6h sets the "probe_availability_6h" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableProbeAvailability6h(v *float64) *GroupHealthStateCreate {
	if v != nil {
		_c.SetProbeAvailability6h(*v)
	}
	return _c
}

// SetProbeTtftAvgMs sets the "probe_ttft_avg_ms" field.
func (_c *GroupHealthStateCreate) SetProbeTtftAvgMs(v int) *GroupHealthStateCreate {
	_c.mutation.SetProbeTtftAvgMs(v)
	return _c
}

// SetNillableProbeTtftAvgMs sets the "probe_ttft_avg_ms" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableProbeTtftAvgMs(v *int) *GroupHealthStateCreate {
	if v != nil {
		_c.SetProbeTtftAvgMs(*v)
	}
	return _c
}

// SetProbeTtftP95Ms sets the "probe_ttft_p95_ms" field.
func (_c *GroupHealthStateCreate) SetProbeTtftP95Ms(v int) *GroupHealthStateCreate {
	_c.mutation.SetProbeTtftP95Ms(v)
	return _c
}

// SetNillableProbeTtftP95Ms sets the "probe_ttft_p95_ms" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableProbeTtftP95Ms(v *int) *GroupHealthStateCreate {
	if v != nil {
		_c.SetProbeTtftP95Ms(*v)
	}
	return _c
}

// SetProbeSamples sets the "probe_samples" field.
func (_c *GroupHealthStateCreate) SetProbeSamples(v int) *GroupHealthStateCreate {
	_c.mutation.SetProbeSamples(v)
	return _c
}

// SetNillableProbeSamples sets the "probe_samples" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableProbeSamples(v *int) *GroupHealthStateCreate {
	if v != nil {
		_c.SetProbeSamples(*v)
	}
	return _c
}

// SetRealTtftP50Ms sets the "real_ttft_p50_ms" field.
func (_c *GroupHealthStateCreate) SetRealTtftP50Ms(v int) *GroupHealthStateCreate {
	_c.mutation.SetRealTtftP50Ms(v)
	return _c
}

// SetNillableRealTtftP50Ms sets the "real_ttft_p50_ms" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableRealTtftP50Ms(v *int) *GroupHealthStateCreate {
	if v != nil {
		_c.SetRealTtftP50Ms(*v)
	}
	return _c
}

// SetRealTtftAvgMs sets the "real_ttft_avg_ms" field.
func (_c *GroupHealthStateCreate) SetRealTtftAvgMs(v int) *GroupHealthStateCreate {
	_c.mutation.SetRealTtftAvgMs(v)
	return _c
}

// SetNillableRealTtftAvgMs sets the "real_ttft_avg_ms" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableRealTtftAvgMs(v *int) *GroupHealthStateCreate {
	if v != nil {
		_c.SetRealTtftAvgMs(*v)
	}
	return _c
}

// SetRealTtftP95Ms sets the "real_ttft_p95_ms" field.
func (_c *GroupHealthStateCreate) SetRealTtftP95Ms(v int) *GroupHealthStateCreate {
	_c.mutation.SetRealTtftP95Ms(v)
	return _c
}

// SetNillableRealTtftP95Ms sets the "real_ttft_p95_ms" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableRealTtftP95Ms(v *int) *GroupHealthStateCreate {
	if v != nil {
		_c.SetRealTtftP95Ms(*v)
	}
	return _c
}

// SetRealTtftSamples sets the "real_ttft_samples" field.
func (_c *GroupHealthStateCreate) SetRealTtftSamples(v int) *GroupHealthStateCreate {
	_c.mutation.SetRealTtftSamples(v)
	return _c
}

// SetNillableRealTtftSamples sets the "real_ttft_samples" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableRealTtftSamples(v *int) *GroupHealthStateCreate {
	if v != nil {
		_c.SetRealTtftSamples(*v)
	}
	return _c
}

// SetRealAvailability6h sets the "real_availability_6h" field.
func (_c *GroupHealthStateCreate) SetRealAvailability6h(v float64) *GroupHealthStateCreate {
	_c.mutation.SetRealAvailability6h(v)
	return _c
}

// SetNillableRealAvailability6h sets the "real_availability_6h" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableRealAvailability6h(v *float64) *GroupHealthStateCreate {
	if v != nil {
		_c.SetRealAvailability6h(*v)
	}
	return _c
}

// SetRealTotalAvgMs sets the "real_total_avg_ms" field.
func (_c *GroupHealthStateCreate) SetRealTotalAvgMs(v int) *GroupHealthStateCreate {
	_c.mutation.SetRealTotalAvgMs(v)
	return _c
}

// SetNillableRealTotalAvgMs sets the "real_total_avg_ms" field if the given value is not nil.
func (_c *GroupHealthStateCreate) SetNillableRealTotalAvgMs(v *int) *GroupHealthStateCreate {
	if v != nil {
		_c.SetRealTotalAvgMs(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupHealthStateCreate) SetGroup(v *Group) *GroupHealthStateCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the GroupHealthStateMutation object of the builder.
func (_c *GroupHealthStateCreate) Mutation() *GroupHealthStateMutation {
	return _c.mutation
}

// Save creates the GroupHealthState in the database.
func (_c *GroupHealthStateCreate) Save(ctx context.Context) (*GroupHealthState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupHealthStateCreate) SaveX(ctx context.Context) *GroupHealthState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupHealthStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupHealthStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupHealthStateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := grouphealthstate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := grouphealthstate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := grouphealthstate.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		v := grouphealthstate.DefaultFailureCount
		_c.mutation.SetFailureCount(v)
	}
	if _, ok := _c.mutation.ProbeTtftMs(); !ok {
		v := grouphealthstate.DefaultProbeTtftMs
		_c.mutation.SetProbeTtftMs(v)
	}
	if _, ok := _c.mutation.ProbeAvailability6h(); !ok {
		v := grouphealthstate.DefaultProbeAvailability6h
		_c.mutation.SetProbeAvailability6h(v)
	}
	if _, ok := _c.mutation.ProbeTtftAvgMs(); !ok {
		v := grouphealthstate.DefaultProbeTtftAvgMs
		_c.mutation.SetProbeTtftAvgMs(v)
	}
	if _, ok := _c.mutation.ProbeTtftP95Ms(); !ok {
		v := grouphealthstate.DefaultProbeTtftP95Ms
		_c.mutation.SetProbeTtftP95Ms(v)
	}
	if _, ok := _c.mutation.ProbeSamples(); !ok {
		v := grouphealthstate.DefaultProbeSamples
		_c.mutation.SetProbeSamples(v)
	}
	if _, ok := _c.mutation.RealTtftP50Ms(); !ok {
		v := grouphealthstate.DefaultRealTtftP50Ms
		_c.mutation.SetRealTtftP50Ms(v)
	}
	if _, ok := _c.mutation.RealTtftAvgMs(); !ok {
		v := grouphealthstate.DefaultRealTtftAvgMs
		_c.mutation.SetRealTtftAvgMs(v)
	}
	if _, ok := _c.mutation.RealTtftP95Ms(); !ok {
		v := grouphealthstate.DefaultRealTtftP95Ms
		_c.mutation.SetRealTtftP95Ms(v)
	}
	if _, ok := _c.mutation.RealTtftSamples(); !ok {
		v := grouphealthstate.DefaultRealTtftSamples
		_c.mutation.SetRealTtftSamples(v)
	}
	if _, ok := _c.mutation.RealAvailability6h(); !ok {
		v := grouphealthstate.DefaultRealAvailability6h
		_c.mutation.SetRealAvailability6h(v)
	}
	if _, ok := _c.mutation.RealTotalAvgMs(); !ok {
		v := grouphealthstate.DefaultRealTotalAvgMs
		_c.mutation.SetRealTotalAvgMs(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupHealthStateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupHealthState.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GroupHealthState.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupHealthState.group_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "GroupHealthState.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := grouphealthstate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GroupHealthState.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		return &ValidationError{Name: "failure_count", err: errors.New(`ent: missing required field "GroupHealthState.failure_count"`)}
	}
	if _, ok := _c.mutation.ProbeTtftMs(); !ok {
		return &ValidationError{Name: "probe_ttft_ms", err: errors.New(`ent: missing required field "GroupHealthState.probe_ttft_ms"`)}
	}
	if _, ok := _c.mutation.ProbeAvailability6h(); !ok {
		return &ValidationError{Name: "probe_availability_6h", err: errors.New(`ent: missing required field "GroupHealthState.probe_availability_6h"`)}
	}
	if _, ok := _c.mutation.ProbeTtftAvgMs(); !ok {
		return &ValidationError{Name: "probe_ttft_avg_ms", err: errors.New(`ent: missing required field "GroupHealthState.probe_ttft_avg_ms"`)}
	}
	if _, ok := _c.mutation.ProbeTtftP95Ms(); !ok {
		return &ValidationError{Name: "probe_ttft_p95_ms", err: errors.New(`ent: missing required field "GroupHealthState.probe_ttft_p95_ms"`)}
	}
	if _, ok := _c.mutation.ProbeSamples(); !ok {
		return &ValidationError{Name: "probe_samples", err: errors.New(`ent: missing required field "GroupHealthState.probe_samples"`)}
	}
	if _, ok := _c.mutation.RealTtftP50Ms(); !ok {
		return &ValidationError{Name: "real_ttft_p50_ms", err: errors.New(`ent: missing required field "GroupHealthState.real_ttft_p50_ms"`)}
	}
	if _, ok := _c.mutation.RealTtftAvgMs(); !ok {
		return &ValidationError{Name: "real_ttft_avg_ms", err: errors.New(`ent: missing required field "GroupHealthState.real_ttft_avg_ms"`)}
	}
	if _, ok := _c.mutation.RealTtftP95Ms(); !ok {
		return &ValidationError{Name: "real_ttft_p95_ms", err: errors.New(`ent: missing required field "GroupHealthState.real_ttft_p95_ms"`)}
	}
	if _, ok := _c.mutation.RealTtftSamples(); !ok {
		return &ValidationError{Name: "real_ttft_samples", err: errors.New(`ent: missing required field "GroupHealthState.real_ttft_samples"`)}
	}
	if _, ok := _c.mutation.RealAvailability6h(); !ok {
		return &ValidationError{Name: "real_availability_6h", err: errors.New(`ent: missing required field "GroupHealthState.real_availability_6h"`)}
	}
	if _, ok := _c.mutation.RealTotalAvgMs(); !ok {
		return &ValidationError{Name: "real_total_avg_ms", err: errors.New(`ent: missing required field "GroupHealthState.real_total_avg_ms"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupHealthState.group"`)}
	}
	return nil
}

func (_c *GroupHealthStateCreate) sqlSave(ctx context.Context) (*GroupHealthState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupHealthStateCreate) createSpec() (*GroupHealthState, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupHealthState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(grouphealthstate.Table, sqlgraph.NewFieldSpec(grouphealthstate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(grouphealthstate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(grouphealthstate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(grouphealthstate.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(grouphealthstate.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.LastProbeAt(); ok {
		_spec.SetField(grouphealthstate.FieldLastProbeAt, field.TypeTime, value)
		_node.LastProbeAt = &value
	}
	if value, ok := _c.mutation.LastSuccessAt(); ok {
		_spec.SetField(grouphealthstate.FieldLastSuccessAt, field.TypeTime, value)
		_node.LastSuccessAt = &value
	}
	if value, ok := _c.mutation.NextProbeAt(); ok {
		_spec.SetField(grouphealthstate.FieldNextProbeAt, field.TypeTime, value)
		_node.NextProbeAt = &value
	}
	if value, ok := _c.mutation.FailureCount(); ok {
		_spec.SetField(grouphealthstate.FieldFailureCount, field.TypeInt, value)
		_node.FailureCount = value
	}
	if value, ok := _c.mutation.ProbeTtftMs(); ok {
		_spec.SetField(grouphealthstate.FieldProbeTtftMs, field.TypeInt, value)
		_node.ProbeTtftMs = value
	}
	if value, ok := _c.mutation.ProbeAvailability6h(); ok {
		_spec.SetField(grouphealthstate.FieldProbeAvailability6h, field.TypeFloat64, value)
		_node.ProbeAvailability6h = value
	}
	if value, ok := _c.mutation.ProbeTtftAvgMs(); ok {
		_spec.SetField(grouphealthstate.FieldProbeTtftAvgMs, field.TypeInt, value)
		_node.ProbeTtftAvgMs = value
	}
	if value, ok := _c.mutation.ProbeTtftP95Ms(); ok {
		_spec.SetField(grouphealthstate.FieldProbeTtftP95Ms, field.TypeInt, value)
		_node.ProbeTtftP95Ms = value
	}
	if value, ok := _c.mutation.ProbeSamples(); ok {
		_spec.SetField(grouphealthstate.FieldProbeSamples, field.TypeInt, value)
		_node.ProbeSamples = value
	}
	if value, ok := _c.mutation.RealTtftP50Ms(); ok {
		_spec.SetField(grouphealthstate.FieldRealTtftP50Ms, field.TypeInt, value)
		_node.RealTtftP50Ms = value
	}
	if value, ok := _c.mutation.RealTtftAvgMs(); ok {
		_spec.SetField(grouphealthstate.FieldRealTtftAvgMs, field.TypeInt, value)
		_node.RealTtftAvgMs = value
	}
	if value, ok := _c.mutation.RealTtftP95Ms(); ok {
		_spec.SetField(grouphealthstate.FieldRealTtftP95Ms, field.TypeInt, value)
		_node.RealTtftP95Ms = value
	}
	if value, ok := _c.mutation.RealTtftSamples(); ok {
		_spec.SetField(grouphealthstate.FieldRealTtftSamples, field.TypeInt, value)
		_node.RealTtftSamples = value
	}
	if value, ok := _c.mutation.RealAvailability6h(); ok {
		_spec.SetField(grouphealthstate.FieldRealAvailability6h, field.TypeFloat64, value)
		_node.RealAvailability6h = value
	}
	if value, ok := _c.mutation.RealTotalAvgMs(); ok {
		_spec.SetField(grouphealthstate.FieldRealTotalAvgMs, field.TypeInt, value)
		_node.RealTotalAvgMs = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grouphealthstate.GroupTable,
			Columns: []string{grouphealthstate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupHealthState.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupHealthStateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupHealthStateCreate) OnConflict(opts ...sql.ConflictOption) *GroupHealthStateUpsertOne {
	_c.conflict = opts
	return &GroupHealthStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupHealthState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupHealthStateCreate) OnConflictColumns(columns ...string) *GroupHealthStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupHealthStateUpsertOne{
		create: _c,
	}
}

type (
	// GroupHealthStateUpsertOne is the builder for "upsert"-ing
	//  one GroupHealthState node.
	GroupHealthStateUpsertOne struct {
		create *GroupHealthStateCreate
	}

	// GroupHealthStateUpsert is the "OnConflict" setter.
	GroupHealthStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupHealthStateUpsert) SetUpdatedAt(v time.Time) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateUpdatedAt() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldUpdatedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupHealthStateUpsert) SetGroupID(v int64) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateGroupID() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldGroupID)
	return u
}

// SetStatus sets the "status" field.
func (u *GroupHealthStateUpsert) SetStatus(v string) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateStatus() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldStatus)
	return u
}

// SetReason sets the "reason" field.
func (u *GroupHealthStateUpsert) SetReason(v string) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateReason() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *GroupHealthStateUpsert) ClearReason() *GroupHealthStateUpsert {
	u.SetNull(grouphealthstate.FieldReason)
	return u
}

// SetLastProbeAt sets the "last_probe_at" field.
func (u *GroupHealthStateUpsert) SetLastProbeAt(v time.Time) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldLastProbeAt, v)
	return u
}

// UpdateLastProbeAt sets the "last_probe_at" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateLastProbeAt() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldLastProbeAt)
	return u
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (u *GroupHealthStateUpsert) ClearLastProbeAt() *GroupHealthStateUpsert {
	u.SetNull(grouphealthstate.FieldLastProbeAt)
	return u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *GroupHealthStateUpsert) SetLastSuccessAt(v time.Time) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldLastSuccessAt, v)
	return u
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateLastSuccessAt() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldLastSuccessAt)
	return u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *GroupHealthStateUpsert) ClearLastSuccessAt() *GroupHealthStateUpsert {
	u.SetNull(grouphealthstate.FieldLastSuccessAt)
	return u
}

// SetNextProbeAt sets the "next_probe_at" field.
func (u *GroupHealthStateUpsert) SetNextProbeAt(v time.Time) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldNextProbeAt, v)
	return u
}

// UpdateNextProbeAt sets the "next_probe_at" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateNextProbeAt() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldNextProbeAt)
	return u
}

// ClearNextProbeAt clears the value of the "next_probe_at" field.
func (u *GroupHealthStateUpsert) ClearNextProbeAt() *GroupHealthStateUpsert {
	u.SetNull(grouphealthstate.FieldNextProbeAt)
	return u
}

// SetFailureCount sets the "failure_count" field.
func (u *GroupHealthStateUpsert) SetFailureCount(v int) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldFailureCount, v)
	return u
}

// UpdateFailureCount sets the "failure_count" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateFailureCount() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldFailureCount)
	return u
}

// AddFailureCount adds v to the "failure_count" field.
func (u *GroupHealthStateUpsert) AddFailureCount(v int) *GroupHealthStateUpsert {
	u.Add(grouphealthstate.FieldFailureCount, v)
	return u
}

// SetProbeTtftMs sets the "probe_ttft_ms" field.
func (u *GroupHealthStateUpsert) SetProbeTtftMs(v int) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldProbeTtftMs, v)
	return u
}

// UpdateProbeTtftMs sets the "probe_ttft_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateProbeTtftMs() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldProbeTtftMs)
	return u
}

// AddProbeTtftMs adds v to the "probe_ttft_ms" field.
func (u *GroupHealthStateUpsert) AddProbeTtftMs(v int) *GroupHealthStateUpsert {
	u.Add(grouphealthstate.FieldProbeTtftMs, v)
	return u
}

// SetProbeAvailability6h sets the "probe_availability_6h" field.
func (u *GroupHealthStateUpsert) SetProbeAvailability6h(v float64) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldProbeAvailability6h, v)
	return u
}

// UpdateProbeAvailability6h sets the "probe_availability_6h" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateProbeAvailability6h() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldProbeAvailability6h)
	return u
}

// AddProbeAvailability6h adds v to the "probe_availability_6h" field.
func (u *GroupHealthStateUpsert) AddProbeAvailability6h(v float64) *GroupHealthStateUpsert {
	u.Add(grouphealthstate.FieldProbeAvailability6h, v)
	return u
}

// SetProbeTtftAvgMs sets the "probe_ttft_avg_ms" field.
func (u *GroupHealthStateUpsert) SetProbeTtftAvgMs(v int) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldProbeTtftAvgMs, v)
	return u
}

// UpdateProbeTtftAvgMs sets the "probe_ttft_avg_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateProbeTtftAvgMs() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldProbeTtftAvgMs)
	return u
}

// AddProbeTtftAvgMs adds v to the "probe_ttft_avg_ms" field.
func (u *GroupHealthStateUpsert) AddProbeTtftAvgMs(v int) *GroupHealthStateUpsert {
	u.Add(grouphealthstate.FieldProbeTtftAvgMs, v)
	return u
}

// SetProbeTtftP95Ms sets the "probe_ttft_p95_ms" field.
func (u *GroupHealthStateUpsert) SetProbeTtftP95Ms(v int) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldProbeTtftP95Ms, v)
	return u
}

// UpdateProbeTtftP95Ms sets the "probe_ttft_p95_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateProbeTtftP95Ms() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldProbeTtftP95Ms)
	return u
}

// AddProbeTtftP95Ms adds v to the "probe_ttft_p95_ms" field.
func (u *GroupHealthStateUpsert) AddProbeTtftP95Ms(v int) *GroupHealthStateUpsert {
	u.Add(grouphealthstate.FieldProbeTtftP95Ms, v)
	return u
}

// SetProbeSamples sets the "probe_samples" field.
func (u *GroupHealthStateUpsert) SetProbeSamples(v int) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldProbeSamples, v)
	return u
}

// UpdateProbeSamples sets the "probe_samples" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateProbeSamples() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldProbeSamples)
	return u
}

// AddProbeSamples adds v to the "probe_samples" field.
func (u *GroupHealthStateUpsert) AddProbeSamples(v int) *GroupHealthStateUpsert {
	u.Add(grouphealthstate.FieldProbeSamples, v)
	return u
}

// SetRealTtftP50Ms sets the "real_ttft_p50_ms" field.
func (u *GroupHealthStateUpsert) SetRealTtftP50Ms(v int) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldRealTtftP50Ms, v)
	return u
}

// UpdateRealTtftP50Ms sets the "real_ttft_p50_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateRealTtftP50Ms() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldRealTtftP50Ms)
	return u
}

// AddRealTtftP50Ms adds v to the "real_ttft_p50_ms" field.
func (u *GroupHealthStateUpsert) AddRealTtftP50Ms(v int) *GroupHealthStateUpsert {
	u.Add(grouphealthstate.FieldRealTtftP50Ms, v)
	return u
}

// SetRealTtftAvgMs sets the "real_ttft_avg_ms" field.
func (u *GroupHealthStateUpsert) SetRealTtftAvgMs(v int) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldRealTtftAvgMs, v)
	return u
}

// UpdateRealTtftAvgMs sets the "real_ttft_avg_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateRealTtftAvgMs() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldRealTtftAvgMs)
	return u
}

// AddRealTtftAvgMs adds v to the "real_ttft_avg_ms" field.
func (u *GroupHealthStateUpsert) AddRealTtftAvgMs(v int) *GroupHealthStateUpsert {
	u.Add(grouphealthstate.FieldRealTtftAvgMs, v)
	return u
}

// SetRealTtftP95Ms sets the "real_ttft_p95_ms" field.
func (u *GroupHealthStateUpsert) SetRealTtftP95Ms(v int) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldRealTtftP95Ms, v)
	return u
}

// UpdateRealTtftP95Ms sets the "real_ttft_p95_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateRealTtftP95Ms() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldRealTtftP95Ms)
	return u
}

// AddRealTtftP95Ms adds v to the "real_ttft_p95_ms" field.
func (u *GroupHealthStateUpsert) AddRealTtftP95Ms(v int) *GroupHealthStateUpsert {
	u.Add(grouphealthstate.FieldRealTtftP95Ms, v)
	return u
}

// SetRealTtftSamples sets the "real_ttft_samples" field.
func (u *GroupHealthStateUpsert) SetRealTtftSamples(v int) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldRealTtftSamples, v)
	return u
}

// UpdateRealTtftSamples sets the "real_ttft_samples" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateRealTtftSamples() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldRealTtftSamples)
	return u
}

// AddRealTtftSamples adds v to the "real_ttft_samples" field.
func (u *GroupHealthStateUpsert) AddRealTtftSamples(v int) *GroupHealthStateUpsert {
	u.Add(grouphealthstate.FieldRealTtftSamples, v)
	return u
}

// SetRealAvailability6h sets the "real_availability_6h" field.
func (u *GroupHealthStateUpsert) SetRealAvailability6h(v float64) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldRealAvailability6h, v)
	return u
}

// UpdateRealAvailability6h sets the "real_availability_6h" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateRealAvailability6h() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldRealAvailability6h)
	return u
}

// AddRealAvailability6h adds v to the "real_availability_6h" field.
func (u *GroupHealthStateUpsert) AddRealAvailability6h(v float64) *GroupHealthStateUpsert {
	u.Add(grouphealthstate.FieldRealAvailability6h, v)
	return u
}

// SetRealTotalAvgMs sets the "real_total_avg_ms" field.
func (u *GroupHealthStateUpsert) SetRealTotalAvgMs(v int) *GroupHealthStateUpsert {
	u.Set(grouphealthstate.FieldRealTotalAvgMs, v)
	return u
}

// UpdateRealTotalAvgMs sets the "real_total_avg_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsert) UpdateRealTotalAvgMs() *GroupHealthStateUpsert {
	u.SetExcluded(grouphealthstate.FieldRealTotalAvgMs)
	return u
}

// AddRealTotalAvgMs adds v to the "real_total_avg_ms" field.
func (u *GroupHealthStateUpsert) AddRealTotalAvgMs(v int) *GroupHealthStateUpsert {
	u.Add(grouphealthstate.FieldRealTotalAvgMs, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupHealthState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupHealthStateUpsertOne) UpdateNewValues() *GroupHealthStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(grouphealthstate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupHealthState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupHealthStateUpsertOne) Ignore() *GroupHealthStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupHealthStateUpsertOne) DoNothing() *GroupHealthStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupHealthStateCreate.OnConflict
// documentation for more info.
func (u *GroupHealthStateUpsertOne) Update(set func(*GroupHealthStateUpsert)) *GroupHealthStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupHealthStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupHealthStateUpsertOne) SetUpdatedAt(v time.Time) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateUpdatedAt() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupHealthStateUpsertOne) SetGroupID(v int64) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateGroupID() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateGroupID()
	})
}

// SetStatus sets the "status" field.
func (u *GroupHealthStateUpsertOne) SetStatus(v string) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateStatus() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *GroupHealthStateUpsertOne) SetReason(v string) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateReason() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *GroupHealthStateUpsertOne) ClearReason() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.ClearReason()
	})
}

// SetLastProbeAt sets the "last_probe_at" field.
func (u *GroupHealthStateUpsertOne) SetLastProbeAt(v time.Time) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetLastProbeAt(v)
	})
}

// UpdateLastProbeAt sets the "last_probe_at" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateLastProbeAt() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateLastProbeAt()
	})
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (u *GroupHealthStateUpsertOne) ClearLastProbeAt() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.ClearLastProbeAt()
	})
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *GroupHealthStateUpsertOne) SetLastSuccessAt(v time.Time) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetLastSuccessAt(v)
	})
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateLastSuccessAt() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateLastSuccessAt()
	})
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *GroupHealthStateUpsertOne) ClearLastSuccessAt() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.ClearLastSuccessAt()
	})
}

// SetNextProbeAt sets the "next_probe_at" field.
func (u *GroupHealthStateUpsertOne) SetNextProbeAt(v time.Time) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetNextProbeAt(v)
	})
}

// UpdateNextProbeAt sets the "next_probe_at" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateNextProbeAt() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateNextProbeAt()
	})
}

// ClearNextProbeAt clears the value of the "next_probe_at" field.
func (u *GroupHealthStateUpsertOne) ClearNextProbeAt() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.ClearNextProbeAt()
	})
}

// SetFailureCount sets the "failure_count" field.
func (u *GroupHealthStateUpsertOne) SetFailureCount(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetFailureCount(v)
	})
}

// AddFailureCount adds v to the "failure_count" field.
func (u *GroupHealthStateUpsertOne) AddFailureCount(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddFailureCount(v)
	})
}

// UpdateFailureCount sets the "failure_count" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateFailureCount() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateFailureCount()
	})
}

// SetProbeTtftMs sets the "probe_ttft_ms" field.
func (u *GroupHealthStateUpsertOne) SetProbeTtftMs(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetProbeTtftMs(v)
	})
}

// AddProbeTtftMs adds v to the "probe_ttft_ms" field.
func (u *GroupHealthStateUpsertOne) AddProbeTtftMs(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddProbeTtftMs(v)
	})
}

// UpdateProbeTtftMs sets the "probe_ttft_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateProbeTtftMs() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateProbeTtftMs()
	})
}

// SetProbeAvailability6h sets the "probe_availability_6h" field.
func (u *GroupHealthStateUpsertOne) SetProbeAvailability6h(v float64) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetProbeAvailability6h(v)
	})
}

// AddProbeAvailability6h adds v to the "probe_availability_6h" field.
func (u *GroupHealthStateUpsertOne) AddProbeAvailability6h(v float64) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddProbeAvailability6h(v)
	})
}

// UpdateProbeAvailability6h sets the "probe_availability_6h" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateProbeAvailability6h() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateProbeAvailability6h()
	})
}

// SetProbeTtftAvgMs sets the "probe_ttft_avg_ms" field.
func (u *GroupHealthStateUpsertOne) SetProbeTtftAvgMs(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetProbeTtftAvgMs(v)
	})
}

// AddProbeTtftAvgMs adds v to the "probe_ttft_avg_ms" field.
func (u *GroupHealthStateUpsertOne) AddProbeTtftAvgMs(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddProbeTtftAvgMs(v)
	})
}

// UpdateProbeTtftAvgMs sets the "probe_ttft_avg_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateProbeTtftAvgMs() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateProbeTtftAvgMs()
	})
}

// SetProbeTtftP95Ms sets the "probe_ttft_p95_ms" field.
func (u *GroupHealthStateUpsertOne) SetProbeTtftP95Ms(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetProbeTtftP95Ms(v)
	})
}

// AddProbeTtftP95Ms adds v to the "probe_ttft_p95_ms" field.
func (u *GroupHealthStateUpsertOne) AddProbeTtftP95Ms(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddProbeTtftP95Ms(v)
	})
}

// UpdateProbeTtftP95Ms sets the "probe_ttft_p95_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateProbeTtftP95Ms() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateProbeTtftP95Ms()
	})
}

// SetProbeSamples sets the "probe_samples" field.
func (u *GroupHealthStateUpsertOne) SetProbeSamples(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetProbeSamples(v)
	})
}

// AddProbeSamples adds v to the "probe_samples" field.
func (u *GroupHealthStateUpsertOne) AddProbeSamples(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddProbeSamples(v)
	})
}

// UpdateProbeSamples sets the "probe_samples" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateProbeSamples() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateProbeSamples()
	})
}

// SetRealTtftP50Ms sets the "real_ttft_p50_ms" field.
func (u *GroupHealthStateUpsertOne) SetRealTtftP50Ms(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetRealTtftP50Ms(v)
	})
}

// AddRealTtftP50Ms adds v to the "real_ttft_p50_ms" field.
func (u *GroupHealthStateUpsertOne) AddRealTtftP50Ms(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddRealTtftP50Ms(v)
	})
}

// UpdateRealTtftP50Ms sets the "real_ttft_p50_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateRealTtftP50Ms() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateRealTtftP50Ms()
	})
}

// SetRealTtftAvgMs sets the "real_ttft_avg_ms" field.
func (u *GroupHealthStateUpsertOne) SetRealTtftAvgMs(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetRealTtftAvgMs(v)
	})
}

// AddRealTtftAvgMs adds v to the "real_ttft_avg_ms" field.
func (u *GroupHealthStateUpsertOne) AddRealTtftAvgMs(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddRealTtftAvgMs(v)
	})
}

// UpdateRealTtftAvgMs sets the "real_ttft_avg_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateRealTtftAvgMs() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateRealTtftAvgMs()
	})
}

// SetRealTtftP95Ms sets the "real_ttft_p95_ms" field.
func (u *GroupHealthStateUpsertOne) SetRealTtftP95Ms(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetRealTtftP95Ms(v)
	})
}

// AddRealTtftP95Ms adds v to the "real_ttft_p95_ms" field.
func (u *GroupHealthStateUpsertOne) AddRealTtftP95Ms(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddRealTtftP95Ms(v)
	})
}

// UpdateRealTtftP95Ms sets the "real_ttft_p95_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateRealTtftP95Ms() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateRealTtftP95Ms()
	})
}

// SetRealTtftSamples sets the "real_ttft_samples" field.
func (u *GroupHealthStateUpsertOne) SetRealTtftSamples(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetRealTtftSamples(v)
	})
}

// AddRealTtftSamples adds v to the "real_ttft_samples" field.
func (u *GroupHealthStateUpsertOne) AddRealTtftSamples(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddRealTtftSamples(v)
	})
}

// UpdateRealTtftSamples sets the "real_ttft_samples" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateRealTtftSamples() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateRealTtftSamples()
	})
}

// SetRealAvailability6h sets the "real_availability_6h" field.
func (u *GroupHealthStateUpsertOne) SetRealAvailability6h(v float64) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetRealAvailability6h(v)
	})
}

// AddRealAvailability6h adds v to the "real_availability_6h" field.
func (u *GroupHealthStateUpsertOne) AddRealAvailability6h(v float64) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddRealAvailability6h(v)
	})
}

// UpdateRealAvailability6h sets the "real_availability_6h" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateRealAvailability6h() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateRealAvailability6h()
	})
}

// SetRealTotalAvgMs sets the "real_total_avg_ms" field.
func (u *GroupHealthStateUpsertOne) SetRealTotalAvgMs(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetRealTotalAvgMs(v)
	})
}

// AddRealTotalAvgMs adds v to the "real_total_avg_ms" field.
func (u *GroupHealthStateUpsertOne) AddRealTotalAvgMs(v int) *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddRealTotalAvgMs(v)
	})
}

// UpdateRealTotalAvgMs sets the "real_total_avg_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertOne) UpdateRealTotalAvgMs() *GroupHealthStateUpsertOne {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateRealTotalAvgMs()
	})
}

// Exec executes the query.
func (u *GroupHealthStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupHealthStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupHealthStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupHealthStateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupHealthStateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupHealthStateCreateBulk is the builder for creating many GroupHealthState entities in bulk.
type GroupHealthStateCreateBulk struct {
	config
	err      error
	builders []*GroupHealthStateCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupHealthState entities in the database.
func (_c *GroupHealthStateCreateBulk) Save(ctx context.Context) ([]*GroupHealthState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupHealthState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupHealthStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupHealthStateCreateBulk) SaveX(ctx context.Context) []*GroupHealthState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupHealthStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupHealthStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupHealthState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupHealthStateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupHealthStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupHealthStateUpsertBulk {
	_c.conflict = opts
	return &GroupHealthStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupHealthState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupHealthStateCreateBulk) OnConflictColumns(columns ...string) *GroupHealthStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupHealthStateUpsertBulk{
		create: _c,
	}
}

// GroupHealthStateUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupHealthState nodes.
type GroupHealthStateUpsertBulk struct {
	create *GroupHealthStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupHealthState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupHealthStateUpsertBulk) UpdateNewValues() *GroupHealthStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(grouphealthstate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupHealthState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupHealthStateUpsertBulk) Ignore() *GroupHealthStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupHealthStateUpsertBulk) DoNothing() *GroupHealthStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupHealthStateCreateBulk.OnConflict
// documentation for more info.
func (u *GroupHealthStateUpsertBulk) Update(set func(*GroupHealthStateUpsert)) *GroupHealthStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupHealthStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupHealthStateUpsertBulk) SetUpdatedAt(v time.Time) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateUpdatedAt() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupHealthStateUpsertBulk) SetGroupID(v int64) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateGroupID() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateGroupID()
	})
}

// SetStatus sets the "status" field.
func (u *GroupHealthStateUpsertBulk) SetStatus(v string) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateStatus() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *GroupHealthStateUpsertBulk) SetReason(v string) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateReason() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *GroupHealthStateUpsertBulk) ClearReason() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.ClearReason()
	})
}

// SetLastProbeAt sets the "last_probe_at" field.
func (u *GroupHealthStateUpsertBulk) SetLastProbeAt(v time.Time) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetLastProbeAt(v)
	})
}

// UpdateLastProbeAt sets the "last_probe_at" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateLastProbeAt() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateLastProbeAt()
	})
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (u *GroupHealthStateUpsertBulk) ClearLastProbeAt() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.ClearLastProbeAt()
	})
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *GroupHealthStateUpsertBulk) SetLastSuccessAt(v time.Time) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetLastSuccessAt(v)
	})
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateLastSuccessAt() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateLastSuccessAt()
	})
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *GroupHealthStateUpsertBulk) ClearLastSuccessAt() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.ClearLastSuccessAt()
	})
}

// SetNextProbeAt sets the "next_probe_at" field.
func (u *GroupHealthStateUpsertBulk) SetNextProbeAt(v time.Time) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetNextProbeAt(v)
	})
}

// UpdateNextProbeAt sets the "next_probe_at" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateNextProbeAt() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateNextProbeAt()
	})
}

// ClearNextProbeAt clears the value of the "next_probe_at" field.
func (u *GroupHealthStateUpsertBulk) ClearNextProbeAt() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.ClearNextProbeAt()
	})
}

// SetFailureCount sets the "failure_count" field.
func (u *GroupHealthStateUpsertBulk) SetFailureCount(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetFailureCount(v)
	})
}

// AddFailureCount adds v to the "failure_count" field.
func (u *GroupHealthStateUpsertBulk) AddFailureCount(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddFailureCount(v)
	})
}

// UpdateFailureCount sets the "failure_count" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateFailureCount() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateFailureCount()
	})
}

// SetProbeTtftMs sets the "probe_ttft_ms" field.
func (u *GroupHealthStateUpsertBulk) SetProbeTtftMs(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetProbeTtftMs(v)
	})
}

// AddProbeTtftMs adds v to the "probe_ttft_ms" field.
func (u *GroupHealthStateUpsertBulk) AddProbeTtftMs(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddProbeTtftMs(v)
	})
}

// UpdateProbeTtftMs sets the "probe_ttft_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateProbeTtftMs() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateProbeTtftMs()
	})
}

// SetProbeAvailability6h sets the "probe_availability_6h" field.
func (u *GroupHealthStateUpsertBulk) SetProbeAvailability6h(v float64) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetProbeAvailability6h(v)
	})
}

// AddProbeAvailability6h adds v to the "probe_availability_6h" field.
func (u *GroupHealthStateUpsertBulk) AddProbeAvailability6h(v float64) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddProbeAvailability6h(v)
	})
}

// UpdateProbeAvailability6h sets the "probe_availability_6h" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateProbeAvailability6h() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateProbeAvailability6h()
	})
}

// SetProbeTtftAvgMs sets the "probe_ttft_avg_ms" field.
func (u *GroupHealthStateUpsertBulk) SetProbeTtftAvgMs(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetProbeTtftAvgMs(v)
	})
}

// AddProbeTtftAvgMs adds v to the "probe_ttft_avg_ms" field.
func (u *GroupHealthStateUpsertBulk) AddProbeTtftAvgMs(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddProbeTtftAvgMs(v)
	})
}

// UpdateProbeTtftAvgMs sets the "probe_ttft_avg_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateProbeTtftAvgMs() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateProbeTtftAvgMs()
	})
}

// SetProbeTtftP95Ms sets the "probe_ttft_p95_ms" field.
func (u *GroupHealthStateUpsertBulk) SetProbeTtftP95Ms(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetProbeTtftP95Ms(v)
	})
}

// AddProbeTtftP95Ms adds v to the "probe_ttft_p95_ms" field.
func (u *GroupHealthStateUpsertBulk) AddProbeTtftP95Ms(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddProbeTtftP95Ms(v)
	})
}

// UpdateProbeTtftP95Ms sets the "probe_ttft_p95_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateProbeTtftP95Ms() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateProbeTtftP95Ms()
	})
}

// SetProbeSamples sets the "probe_samples" field.
func (u *GroupHealthStateUpsertBulk) SetProbeSamples(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetProbeSamples(v)
	})
}

// AddProbeSamples adds v to the "probe_samples" field.
func (u *GroupHealthStateUpsertBulk) AddProbeSamples(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddProbeSamples(v)
	})
}

// UpdateProbeSamples sets the "probe_samples" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateProbeSamples() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateProbeSamples()
	})
}

// SetRealTtftP50Ms sets the "real_ttft_p50_ms" field.
func (u *GroupHealthStateUpsertBulk) SetRealTtftP50Ms(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetRealTtftP50Ms(v)
	})
}

// AddRealTtftP50Ms adds v to the "real_ttft_p50_ms" field.
func (u *GroupHealthStateUpsertBulk) AddRealTtftP50Ms(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddRealTtftP50Ms(v)
	})
}

// UpdateRealTtftP50Ms sets the "real_ttft_p50_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateRealTtftP50Ms() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateRealTtftP50Ms()
	})
}

// SetRealTtftAvgMs sets the "real_ttft_avg_ms" field.
func (u *GroupHealthStateUpsertBulk) SetRealTtftAvgMs(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetRealTtftAvgMs(v)
	})
}

// AddRealTtftAvgMs adds v to the "real_ttft_avg_ms" field.
func (u *GroupHealthStateUpsertBulk) AddRealTtftAvgMs(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddRealTtftAvgMs(v)
	})
}

// UpdateRealTtftAvgMs sets the "real_ttft_avg_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateRealTtftAvgMs() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateRealTtftAvgMs()
	})
}

// SetRealTtftP95Ms sets the "real_ttft_p95_ms" field.
func (u *GroupHealthStateUpsertBulk) SetRealTtftP95Ms(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetRealTtftP95Ms(v)
	})
}

// AddRealTtftP95Ms adds v to the "real_ttft_p95_ms" field.
func (u *GroupHealthStateUpsertBulk) AddRealTtftP95Ms(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddRealTtftP95Ms(v)
	})
}

// UpdateRealTtftP95Ms sets the "real_ttft_p95_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateRealTtftP95Ms() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateRealTtftP95Ms()
	})
}

// SetRealTtftSamples sets the "real_ttft_samples" field.
func (u *GroupHealthStateUpsertBulk) SetRealTtftSamples(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetRealTtftSamples(v)
	})
}

// AddRealTtftSamples adds v to the "real_ttft_samples" field.
func (u *GroupHealthStateUpsertBulk) AddRealTtftSamples(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddRealTtftSamples(v)
	})
}

// UpdateRealTtftSamples sets the "real_ttft_samples" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateRealTtftSamples() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateRealTtftSamples()
	})
}

// SetRealAvailability6h sets the "real_availability_6h" field.
func (u *GroupHealthStateUpsertBulk) SetRealAvailability6h(v float64) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetRealAvailability6h(v)
	})
}

// AddRealAvailability6h adds v to the "real_availability_6h" field.
func (u *GroupHealthStateUpsertBulk) AddRealAvailability6h(v float64) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddRealAvailability6h(v)
	})
}

// UpdateRealAvailability6h sets the "real_availability_6h" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateRealAvailability6h() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateRealAvailability6h()
	})
}

// SetRealTotalAvgMs sets the "real_total_avg_ms" field.
func (u *GroupHealthStateUpsertBulk) SetRealTotalAvgMs(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.SetRealTotalAvgMs(v)
	})
}

// AddRealTotalAvgMs adds v to the "real_total_avg_ms" field.
func (u *GroupHealthStateUpsertBulk) AddRealTotalAvgMs(v int) *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.AddRealTotalAvgMs(v)
	})
}

// UpdateRealTotalAvgMs sets the "real_total_avg_ms" field to the value that was provided on create.
func (u *GroupHealthStateUpsertBulk) UpdateRealTotalAvgMs() *GroupHealthStateUpsertBulk {
	return u.Update(func(s *GroupHealthStateUpsert) {
		s.UpdateRealTotalAvgMs()
	})
}

// Exec executes the query.
func (u *GroupHealthStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupHealthStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupHealthStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupHealthStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
