// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grouphealthevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupHealthEventDelete is the builder for deleting a GroupHealthEvent entity.
type GroupHealthEventDelete struct {
	config
	hooks    []Hook
	mutation *GroupHealthEventMutation
}

// Where appends a list predicates to the GroupHealthEventDelete builder.
func (_d *GroupHealthEventDelete) Where(ps ...predicate.GroupHealthEvent) *GroupHealthEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupHealthEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupHealthEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupHealthEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(grouphealthevent.Table, sqlgraph.NewFieldSpec(grouphealthevent.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupHealthEventDeleteOne is the builder for deleting a single GroupHealthEvent entity.
type GroupHealthEventDeleteOne struct {
	_d *GroupHealthEventDelete
}

// Where appends a list predicates to the GroupHealthEventDelete builder.
func (_d *GroupHealthEventDeleteOne) Where(ps ...predicate.GroupHealthEvent) *GroupHealthEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupHealthEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{grouphealthevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupHealthEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
