// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/grouphealthstate"
)

// GroupHealthState is the model entity for the GroupHealthState schema.
type GroupHealthState struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// LastProbeAt holds the value of the "last_probe_at" field.
	LastProbeAt *time.Time `json:"last_probe_at,omitempty"`
	// LastSuccessAt holds the value of the "last_success_at" field.
	LastSuccessAt *time.Time `json:"last_success_at,omitempty"`
	// NextProbeAt holds the value of the "next_probe_at" field.
	NextProbeAt *time.Time `json:"next_probe_at,omitempty"`
	// FailureCount holds the value of the "failure_count" field.
	FailureCount int `json:"failure_count,omitempty"`
	// ProbeTtftMs holds the value of the "probe_ttft_ms" field.
	ProbeTtftMs int `json:"probe_ttft_ms,omitempty"`
	// ProbeAvailability6h holds the value of the "probe_availability_6h" field.
	ProbeAvailability6h float64 `json:"probe_availability_6h,omitempty"`
	// ProbeTtftAvgMs holds the value of the "probe_ttft_avg_ms" field.
	ProbeTtftAvgMs int `json:"probe_ttft_avg_ms,omitempty"`
	// ProbeTtftP95Ms holds the value of the "probe_ttft_p95_ms" field.
	ProbeTtftP95Ms int `json:"probe_ttft_p95_ms,omitempty"`
	// ProbeSamples holds the value of the "probe_samples" field.
	ProbeSamples int `json:"probe_samples,omitempty"`
	// RealTtftP50Ms holds the value of the "real_ttft_p50_ms" field.
	RealTtftP50Ms int `json:"real_ttft_p50_ms,omitempty"`
	// RealTtftAvgMs holds the value of the "real_ttft_avg_ms" field.
	RealTtftAvgMs int `json:"real_ttft_avg_ms,omitempty"`
	// RealTtftP95Ms holds the value of the "real_ttft_p95_ms" field.
	RealTtftP95Ms int `json:"real_ttft_p95_ms,omitempty"`
	// RealTtftSamples holds the value of the "real_ttft_samples" field.
	RealTtftSamples int `json:"real_ttft_samples,omitempty"`
	// RealAvailability6h holds the value of the "real_availability_6h" field.
	RealAvailability6h float64 `json:"real_availability_6h,omitempty"`
	// RealTotalAvgMs holds the value of the "real_total_avg_ms" field.
	RealTotalAvgMs int `json:"real_total_avg_ms,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupHealthStateQuery when eager-loading is set.
	Edges        GroupHealthStateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupHealthStateEdges holds the relations/edges for other nodes in the graph.
type GroupHealthStateEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupHealthStateEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupHealthState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case grouphealthstate.FieldProbeAvailability6h, grouphealthstate.FieldRealAvailability6h:
			values[i] = new(sql.NullFloat64)
		case grouphealthstate.FieldID, grouphealthstate.FieldGroupID, grouphealthstate.FieldFailureCount, grouphealthstate.FieldProbeTtftMs, grouphealthstate.FieldProbeTtftAvgMs, grouphealthstate.FieldProbeTtftP95Ms, grouphealthstate.FieldProbeSamples, grouphealthstate.FieldRealTtftP50Ms, grouphealthstate.FieldRealTtftAvgMs, grouphealthstate.FieldRealTtftP95Ms, grouphealthstate.FieldRealTtftSamples, grouphealthstate.FieldRealTotalAvgMs:
			values[i] = new(sql.NullInt64)
		case grouphealthstate.FieldStatus, grouphealthstate.FieldReason:
			values[i] = new(sql.NullString)
		case grouphealthstate.FieldCreatedAt, grouphealthstate.FieldUpdatedAt, grouphealthstate.FieldLastProbeAt, grouphealthstate.FieldLastSuccessAt, grouphealthstate.FieldNextProbeAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupHealthState fields.
func (_m *GroupHealthState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case grouphealthstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case grouphealthstate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case grouphealthstate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case grouphealthstate.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case grouphealthstate.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case grouphealthstate.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case grouphealthstate.FieldLastProbeAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_probe_at", values[i])
			} else if value.Valid {
				_m.LastProbeAt = new(time.Time)
				*_m.LastProbeAt = value.Time
			}
		case grouphealthstate.FieldLastSuccessAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_success_at", values[i])
			} else if value.Valid {
				_m.LastSuccessAt = new(time.Time)
				*_m.LastSuccessAt = value.Time
			}
		case grouphealthstate.FieldNextProbeAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_probe_at", values[i])
			} else if value.Valid {
				_m.NextProbeAt = new(time.Time)
				*_m.NextProbeAt = value.Time
			}
		case grouphealthstate.FieldFailureCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failure_count", values[i])
			} else if value.Valid {
				_m.FailureCount = int(value.Int64)
			}
		case grouphealthstate.FieldProbeTtftMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field probe_ttft_ms", values[i])
			} else if value.Valid {
				_m.ProbeTtftMs = int(value.Int64)
			}
		case grouphealthstate.FieldProbeAvailability6h:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field probe_availability_6h", values[i])
			} else if value.Valid {
				_m.ProbeAvailability6h = value.Float64
			}
		case grouphealthstate.FieldProbeTtftAvgMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field probe_ttft_avg_ms", values[i])
			} else if value.Valid {
				_m.ProbeTtftAvgMs = int(value.Int64)
			}
		case grouphealthstate.FieldProbeTtftP95Ms:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field probe_ttft_p95_ms", values[i])
			} else if value.Valid {
				_m.ProbeTtftP95Ms = int(value.Int64)
			}
		case grouphealthstate.FieldProbeSamples:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field probe_samples", values[i])
			} else if value.Valid {
				_m.ProbeSamples = int(value.Int64)
			}
		case grouphealthstate.FieldRealTtftP50Ms:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field real_ttft_p50_ms", values[i])
			} else if value.Valid {
				_m.RealTtftP50Ms = int(value.Int64)
			}
		case grouphealthstate.FieldRealTtftAvgMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field real_ttft_avg_ms", values[i])
			} else if value.Valid {
				_m.RealTtftAvgMs = int(value.Int64)
			}
		case grouphealthstate.FieldRealTtftP95Ms:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field real_ttft_p95_ms", values[i])
			} else if value.Valid {
				_m.RealTtftP95Ms = int(value.Int64)
			}
		case grouphealthstate.FieldRealTtftSamples:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field real_ttft_samples", values[i])
			} else if value.Valid {
				_m.RealTtftSamples = int(value.Int64)
			}
		case grouphealthstate.FieldRealAvailability6h:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field real_availability_6h", values[i])
			} else if value.Valid {
				_m.RealAvailability6h = value.Float64
			}
		case grouphealthstate.FieldRealTotalAvgMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field real_total_avg_ms", values[i])
			} else if value.Valid {
				_m.RealTotalAvgMs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupHealthState.
// This includes values selected through modifiers, order, etc.
func (_m *GroupHealthState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the GroupHealthState entity.
func (_m *GroupHealthState) QueryGroup() *GroupQuery {
	return NewGroupHealthStateClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this GroupHealthState.
// Note that you need to call GroupHealthState.Unwrap() before calling this method if this GroupHealthState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupHealthState) Update() *GroupHealthStateUpdateOne {
	return NewGroupHealthStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupHealthState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupHealthState) Unwrap() *GroupHealthState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupHealthState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupHealthState) String() string {
	var builder strings.Builder
	builder.WriteString("GroupHealthState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastProbeAt; v != nil {
		builder.WriteString("last_probe_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastSuccessAt; v != nil {
		builder.WriteString("last_success_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextProbeAt; v != nil {
		builder.WriteString("next_probe_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("failure_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailureCount))
	builder.WriteString(", ")
	builder.WriteString("probe_ttft_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProbeTtftMs))
	builder.WriteString(", ")
	builder.WriteString("probe_availability_6h=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProbeAvailability6h))
	builder.WriteString(", ")
	builder.WriteString("probe_ttft_avg_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProbeTtftAvgMs))
	builder.WriteString(", ")
	builder.WriteString("probe_ttft_p95_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProbeTtftP95Ms))
	builder.WriteString(", ")
	builder.WriteString("probe_samples=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProbeSamples))
	builder.WriteString(", ")
	builder.WriteString("real_ttft_p50_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealTtftP50Ms))
	builder.WriteString(", ")
	builder.WriteString("real_ttft_avg_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealTtftAvgMs))
	builder.WriteString(", ")
	builder.WriteString("real_ttft_p95_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealTtftP95Ms))
	builder.WriteString(", ")
	builder.WriteString("real_ttft_samples=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealTtftSamples))
	builder.WriteString(", ")
	builder.WriteString("real_availability_6h=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealAvailability6h))
	builder.WriteString(", ")
	builder.WriteString("real_total_avg_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealTotalAvgMs))
	builder.WriteByte(')')
	return builder.String()
}

// GroupHealthStates is a parsable slice of GroupHealthState.
type GroupHealthStates []*GroupHealthState
