// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/grouphealthstate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupHealthStateUpdate is the builder for updating GroupHealthState entities.
type GroupHealthStateUpdate struct {
	config
	hooks    []Hook
	mutation *GroupHealthStateMutation
}

// Where appends a list predicates to the GroupHealthStateUpdate builder.
func (_u *GroupHealthStateUpdate) Where(ps ...predicate.GroupHealthState) *GroupHealthStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupHealthStateUpdate) SetUpdatedAt(v time.Time) *GroupHealthStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupHealthStateUpdate) SetGroupID(v int64) *GroupHealthStateUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableGroupID(v *int64) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GroupHealthStateUpdate) SetStatus(v string) *GroupHealthStateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableStatus(v *string) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *GroupHealthStateUpdate) SetReason(v string) *GroupHealthStateUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableReason(v *string) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *GroupHealthStateUpdate) ClearReason() *GroupHealthStateUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetLastProbeAt sets the "last_probe_at" field.
func (_u *GroupHealthStateUpdate) SetLastProbeAt(v time.Time) *GroupHealthStateUpdate {
	_u.mutation.SetLastProbeAt(v)
	return _u
}

// SetNillableLastProbeAt sets the "last_probe_at" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableLastProbeAt(v *time.Time) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetLastProbeAt(*v)
	}
	return _u
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (_u *GroupHealthStateUpdate) ClearLastProbeAt() *GroupHealthStateUpdate {
	_u.mutation.ClearLastProbeAt()
	return _u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_u *GroupHealthStateUpdate) SetLastSuccessAt(v time.Time) *GroupHealthStateUpdate {
	_u.mutation.SetLastSuccessAt(v)
	return _u
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableLastSuccessAt(v *time.Time) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetLastSuccessAt(*v)
	}
	return _u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (_u *GroupHealthStateUpdate) ClearLastSuccessAt() *GroupHealthStateUpdate {
	_u.mutation.ClearLastSuccessAt()
	return _u
}

// SetNextProbeAt sets the "next_probe_at" field.
func (_u *GroupHealthStateUpdate) SetNextProbeAt(v time.Time) *GroupHealthStateUpdate {
	_u.mutation.SetNextProbeAt(v)
	return _u
}

// SetNillableNextProbeAt sets the "next_probe_at" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableNextProbeAt(v *time.Time) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetNextProbeAt(*v)
	}
	return _u
}

// ClearNextProbeAt clears the value of the "next_probe_at" field.
func (_u *GroupHealthStateUpdate) ClearNextProbeAt() *GroupHealthStateUpdate {
	_u.mutation.ClearNextProbeAt()
	return _u
}

// SetFailureCount sets the "failure_count" field.
func (_u *GroupHealthStateUpdate) SetFailureCount(v int) *GroupHealthStateUpdate {
	_u.mutation.ResetFailureCount()
	_u.mutation.SetFailureCount(v)
	return _u
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableFailureCount(v *int) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetFailureCount(*v)
	}
	return _u
}

// AddFailureCount adds value to the "failure_count" field.
func (_u *GroupHealthStateUpdate) AddFailureCount(v int) *GroupHealthStateUpdate {
	_u.mutation.AddFailureCount(v)
	return _u
}

// SetProbeTtftMs sets the "probe_ttft_ms" field.
func (_u *GroupHealthStateUpdate) SetProbeTtftMs(v int) *GroupHealthStateUpdate {
	_u.mutation.ResetProbeTtftMs()
	_u.mutation.SetProbeTtftMs(v)
	return _u
}

// SetNillableProbeTtftMs sets the "probe_ttft_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableProbeTtftMs(v *int) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetProbeTtftMs(*v)
	}
	return _u
}

// AddProbeTtftMs adds value to the "probe_ttft_ms" field.
func (_u *GroupHealthStateUpdate) AddProbeTtftMs(v int) *GroupHealthStateUpdate {
	_u.mutation.AddProbeTtftMs(v)
	return _u
}

// SetProbeAvailability6h sets the "probe_availability_6h" field.
func (_u *GroupHealthStateUpdate) SetProbeAvailability6h(v float64) *GroupHealthStateUpdate {
	_u.mutation.ResetProbeAvailability6h()
	_u.mutation.SetProbeAvailability6h(v)
	return _u
}

// SetNillableProbeAvailability6h sets the "probe_availability_6h" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableProbeAvailability6h(v *float64) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetProbeAvailability6h(*v)
	}
	return _u
}

// AddProbeAvailability6h adds value to the "probe_availability_6h" field.
func (_u *GroupHealthStateUpdate) AddProbeAvailability6h(v float64) *GroupHealthStateUpdate {
	_u.mutation.AddProbeAvailability6h(v)
	return _u
}

// SetProbeTtftAvgMs sets the "probe_ttft_avg_ms" field.
func (_u *GroupHealthStateUpdate) SetProbeTtftAvgMs(v int) *GroupHealthStateUpdate {
	_u.mutation.ResetProbeTtftAvgMs()
	_u.mutation.SetProbeTtftAvgMs(v)
	return _u
}

// SetNillableProbeTtftAvgMs sets the "probe_ttft_avg_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableProbeTtftAvgMs(v *int) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetProbeTtftAvgMs(*v)
	}
	return _u
}

// AddProbeTtftAvgMs adds value to the "probe_ttft_avg_ms" field.
func (_u *GroupHealthStateUpdate) AddProbeTtftAvgMs(v int) *GroupHealthStateUpdate {
	_u.mutation.AddProbeTtftAvgMs(v)
	return _u
}

// SetProbeTtftP95Ms sets the "probe_ttft_p95_ms" field.
func (_u *GroupHealthStateUpdate) SetProbeTtftP95Ms(v int) *GroupHealthStateUpdate {
	_u.mutation.ResetProbeTtftP95Ms()
	_u.mutation.SetProbeTtftP95Ms(v)
	return _u
}

// SetNillableProbeTtftP95Ms sets the "probe_ttft_p95_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableProbeTtftP95Ms(v *int) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetProbeTtftP95Ms(*v)
	}
	return _u
}

// AddProbeTtftP95Ms adds value to the "probe_ttft_p95_ms" field.
func (_u *GroupHealthStateUpdate) AddProbeTtftP95Ms(v int) *GroupHealthStateUpdate {
	_u.mutation.AddProbeTtftP95Ms(v)
	return _u
}

// SetProbeSamples sets the "probe_samples" field.
func (_u *GroupHealthStateUpdate) SetProbeSamples(v int) *GroupHealthStateUpdate {
	_u.mutation.ResetProbeSamples()
	_u.mutation.SetProbeSamples(v)
	return _u
}

// SetNillableProbeSamples sets the "probe_samples" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableProbeSamples(v *int) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetProbeSamples(*v)
	}
	return _u
}

// AddProbeSamples adds value to the "probe_samples" field.
func (_u *GroupHealthStateUpdate) AddProbeSamples(v int) *GroupHealthStateUpdate {
	_u.mutation.AddProbeSamples(v)
	return _u
}

// SetRealTtftP50Ms sets the "real_ttft_p50_ms" field.
func (_u *GroupHealthStateUpdate) SetRealTtftP50Ms(v int) *GroupHealthStateUpdate {
	_u.mutation.ResetRealTtftP50Ms()
	_u.mutation.SetRealTtftP50Ms(v)
	return _u
}

// SetNillableRealTtftP50Ms sets the "real_ttft_p50_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableRealTtftP50Ms(v *int) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetRealTtftP50Ms(*v)
	}
	return _u
}

// AddRealTtftP50Ms adds value to the "real_ttft_p50_ms" field.
func (_u *GroupHealthStateUpdate) AddRealTtftP50Ms(v int) *GroupHealthStateUpdate {
	_u.mutation.AddRealTtftP50Ms(v)
	return _u
}

// SetRealTtftAvgMs sets the "real_ttft_avg_ms" field.
func (_u *GroupHealthStateUpdate) SetRealTtftAvgMs(v int) *GroupHealthStateUpdate {
	_u.mutation.ResetRealTtftAvgMs()
	_u.mutation.SetRealTtftAvgMs(v)
	return _u
}

// SetNillableRealTtftAvgMs sets the "real_ttft_avg_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableRealTtftAvgMs(v *int) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetRealTtftAvgMs(*v)
	}
	return _u
}

// AddRealTtftAvgMs adds value to the "real_ttft_avg_ms" field.
func (_u *GroupHealthStateUpdate) AddRealTtftAvgMs(v int) *GroupHealthStateUpdate {
	_u.mutation.AddRealTtftAvgMs(v)
	return _u
}

// SetRealTtftP95Ms sets the "real_ttft_p95_ms" field.
func (_u *GroupHealthStateUpdate) SetRealTtftP95Ms(v int) *GroupHealthStateUpdate {
	_u.mutation.ResetRealTtftP95Ms()
	_u.mutation.SetRealTtftP95Ms(v)
	return _u
}

// SetNillableRealTtftP95Ms sets the "real_ttft_p95_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableRealTtftP95Ms(v *int) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetRealTtftP95Ms(*v)
	}
	return _u
}

// AddRealTtftP95Ms adds value to the "real_ttft_p95_ms" field.
func (_u *GroupHealthStateUpdate) AddRealTtftP95Ms(v int) *GroupHealthStateUpdate {
	_u.mutation.AddRealTtftP95Ms(v)
	return _u
}

// SetRealTtftSamples sets the "real_ttft_samples" field.
func (_u *GroupHealthStateUpdate) SetRealTtftSamples(v int) *GroupHealthStateUpdate {
	_u.mutation.ResetRealTtftSamples()
	_u.mutation.SetRealTtftSamples(v)
	return _u
}

// SetNillableRealTtftSamples sets the "real_ttft_samples" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableRealTtftSamples(v *int) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetRealTtftSamples(*v)
	}
	return _u
}

// AddRealTtftSamples adds value to the "real_ttft_samples" field.
func (_u *GroupHealthStateUpdate) AddRealTtftSamples(v int) *GroupHealthStateUpdate {
	_u.mutation.AddRealTtftSamples(v)
	return _u
}

// SetRealAvailability6h sets the "real_availability_6h" field.
func (_u *GroupHealthStateUpdate) SetRealAvailability6h(v float64) *GroupHealthStateUpdate {
	_u.mutation.ResetRealAvailability6h()
	_u.mutation.SetRealAvailability6h(v)
	return _u
}

// SetNillableRealAvailability6h sets the "real_availability_6h" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableRealAvailability6h(v *float64) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetRealAvailability6h(*v)
	}
	return _u
}

// AddRealAvailability6h adds value to the "real_availability_6h" field.
func (_u *GroupHealthStateUpdate) AddRealAvailability6h(v float64) *GroupHealthStateUpdate {
	_u.mutation.AddRealAvailability6h(v)
	return _u
}

// SetRealTotalAvgMs sets the "real_total_avg_ms" field.
func (_u *GroupHealthStateUpdate) SetRealTotalAvgMs(v int) *GroupHealthStateUpdate {
	_u.mutation.ResetRealTotalAvgMs()
	_u.mutation.SetRealTotalAvgMs(v)
	return _u
}

// SetNillableRealTotalAvgMs sets the "real_total_avg_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdate) SetNillableRealTotalAvgMs(v *int) *GroupHealthStateUpdate {
	if v != nil {
		_u.SetRealTotalAvgMs(*v)
	}
	return _u
}

// AddRealTotalAvgMs adds value to the "real_total_avg_ms" field.
func (_u *GroupHealthStateUpdate) AddRealTotalAvgMs(v int) *GroupHealthStateUpdate {
	_u.mutation.AddRealTotalAvgMs(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupHealthStateUpdate) SetGroup(v *Group) *GroupHealthStateUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the GroupHealthStateMutation object of the builder.
func (_u *GroupHealthStateUpdate) Mutation() *GroupHealthStateMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupHealthStateUpdate) ClearGroup() *GroupHealthStateUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupHealthStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupHealthStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupHealthStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupHealthStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupHealthStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grouphealthstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupHealthStateUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := grouphealthstate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GroupHealthState.status": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupHealthState.group"`)
	}
	return nil
}

func (_u *GroupHealthStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grouphealthstate.Table, grouphealthstate.Columns, sqlgraph.NewFieldSpec(grouphealthstate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grouphealthstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(grouphealthstate.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(grouphealthstate.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(grouphealthstate.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.LastProbeAt(); ok {
		_spec.SetField(grouphealthstate.FieldLastProbeAt, field.TypeTime, value)
	}
	if _u.mutation.LastProbeAtCleared() {
		_spec.ClearField(grouphealthstate.FieldLastProbeAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSuccessAt(); ok {
		_spec.SetField(grouphealthstate.FieldLastSuccessAt, field.TypeTime, value)
	}
	if _u.mutation.LastSuccessAtCleared() {
		_spec.ClearField(grouphealthstate.FieldLastSuccessAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextProbeAt(); ok {
		_spec.SetField(grouphealthstate.FieldNextProbeAt, field.TypeTime, value)
	}
	if _u.mutation.NextProbeAtCleared() {
		_spec.ClearField(grouphealthstate.FieldNextProbeAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureCount(); ok {
		_spec.SetField(grouphealthstate.FieldFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailureCount(); ok {
		_spec.AddField(grouphealthstate.FieldFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProbeTtftMs(); ok {
		_spec.SetField(grouphealthstate.FieldProbeTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProbeTtftMs(); ok {
		_spec.AddField(grouphealthstate.FieldProbeTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProbeAvailability6h(); ok {
		_spec.SetField(grouphealthstate.FieldProbeAvailability6h, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProbeAvailability6h(); ok {
		_spec.AddField(grouphealthstate.FieldProbeAvailability6h, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ProbeTtftAvgMs(); ok {
		_spec.SetField(grouphealthstate.FieldProbeTtftAvgMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProbeTtftAvgMs(); ok {
		_spec.AddField(grouphealthstate.FieldProbeTtftAvgMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProbeTtftP95Ms(); ok {
		_spec.SetField(grouphealthstate.FieldProbeTtftP95Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProbeTtftP95Ms(); ok {
		_spec.AddField(grouphealthstate.FieldProbeTtftP95Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProbeSamples(); ok {
		_spec.SetField(grouphealthstate.FieldProbeSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProbeSamples(); ok {
		_spec.AddField(grouphealthstate.FieldProbeSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RealTtftP50Ms(); ok {
		_spec.SetField(grouphealthstate.FieldRealTtftP50Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRealTtftP50Ms(); ok {
		_spec.AddField(grouphealthstate.FieldRealTtftP50Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RealTtftAvgMs(); ok {
		_spec.SetField(grouphealthstate.FieldRealTtftAvgMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRealTtftAvgMs(); ok {
		_spec.AddField(grouphealthstate.FieldRealTtftAvgMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RealTtftP95Ms(); ok {
		_spec.SetField(grouphealthstate.FieldRealTtftP95Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRealTtftP95Ms(); ok {
		_spec.AddField(grouphealthstate.FieldRealTtftP95Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RealTtftSamples(); ok {
		_spec.SetField(grouphealthstate.FieldRealTtftSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRealTtftSamples(); ok {
		_spec.AddField(grouphealthstate.FieldRealTtftSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RealAvailability6h(); ok {
		_spec.SetField(grouphealthstate.FieldRealAvailability6h, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRealAvailability6h(); ok {
		_spec.AddField(grouphealthstate.FieldRealAvailability6h, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RealTotalAvgMs(); ok {
		_spec.SetField(grouphealthstate.FieldRealTotalAvgMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRealTotalAvgMs(); ok {
		_spec.AddField(grouphealthstate.FieldRealTotalAvgMs, field.TypeInt, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grouphealthstate.GroupTable,
			Columns: []string{grouphealthstate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grouphealthstate.GroupTable,
			Columns: []string{grouphealthstate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grouphealthstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupHealthStateUpdateOne is the builder for updating a single GroupHealthState entity.
type GroupHealthStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupHealthStateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupHealthStateUpdateOne) SetUpdatedAt(v time.Time) *GroupHealthStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupHealthStateUpdateOne) SetGroupID(v int64) *GroupHealthStateUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableGroupID(v *int64) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GroupHealthStateUpdateOne) SetStatus(v string) *GroupHealthStateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableStatus(v *string) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *GroupHealthStateUpdateOne) SetReason(v string) *GroupHealthStateUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableReason(v *string) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *GroupHealthStateUpdateOne) ClearReason() *GroupHealthStateUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetLastProbeAt sets the "last_probe_at" field.
func (_u *GroupHealthStateUpdateOne) SetLastProbeAt(v time.Time) *GroupHealthStateUpdateOne {
	_u.mutation.SetLastProbeAt(v)
	return _u
}

// SetNillableLastProbeAt sets the "last_probe_at" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableLastProbeAt(v *time.Time) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetLastProbeAt(*v)
	}
	return _u
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (_u *GroupHealthStateUpdateOne) ClearLastProbeAt() *GroupHealthStateUpdateOne {
	_u.mutation.ClearLastProbeAt()
	return _u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_u *GroupHealthStateUpdateOne) SetLastSuccessAt(v time.Time) *GroupHealthStateUpdateOne {
	_u.mutation.SetLastSuccessAt(v)
	return _u
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableLastSuccessAt(v *time.Time) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetLastSuccessAt(*v)
	}
	return _u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (_u *GroupHealthStateUpdateOne) ClearLastSuccessAt() *GroupHealthStateUpdateOne {
	_u.mutation.ClearLastSuccessAt()
	return _u
}

// SetNextProbeAt sets the "next_probe_at" field.
func (_u *GroupHealthStateUpdateOne) SetNextProbeAt(v time.Time) *GroupHealthStateUpdateOne {
	_u.mutation.SetNextProbeAt(v)
	return _u
}

// SetNillableNextProbeAt sets the "next_probe_at" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableNextProbeAt(v *time.Time) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetNextProbeAt(*v)
	}
	return _u
}

// ClearNextProbeAt clears the value of the "next_probe_at" field.
func (_u *GroupHealthStateUpdateOne) ClearNextProbeAt() *GroupHealthStateUpdateOne {
	_u.mutation.ClearNextProbeAt()
	return _u
}

// SetFailureCount sets the "failure_count" field.
func (_u *GroupHealthStateUpdateOne) SetFailureCount(v int) *GroupHealthStateUpdateOne {
	_u.mutation.ResetFailureCount()
	_u.mutation.SetFailureCount(v)
	return _u
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableFailureCount(v *int) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetFailureCount(*v)
	}
	return _u
}

// AddFailureCount adds value to the "failure_count" field.
func (_u *GroupHealthStateUpdateOne) AddFailureCount(v int) *GroupHealthStateUpdateOne {
	_u.mutation.AddFailureCount(v)
	return _u
}

// SetProbeTtftMs sets the "probe_ttft_ms" field.
func (_u *GroupHealthStateUpdateOne) SetProbeTtftMs(v int) *GroupHealthStateUpdateOne {
	_u.mutation.ResetProbeTtftMs()
	_u.mutation.SetProbeTtftMs(v)
	return _u
}

// SetNillableProbeTtftMs sets the "probe_ttft_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableProbeTtftMs(v *int) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetProbeTtftMs(*v)
	}
	return _u
}

// AddProbeTtftMs adds value to the "probe_ttft_ms" field.
func (_u *GroupHealthStateUpdateOne) AddProbeTtftMs(v int) *GroupHealthStateUpdateOne {
	_u.mutation.AddProbeTtftMs(v)
	return _u
}

// SetProbeAvailability6h sets the "probe_availability_6h" field.
func (_u *GroupHealthStateUpdateOne) SetProbeAvailability6h(v float64) *GroupHealthStateUpdateOne {
	_u.mutation.ResetProbeAvailability6h()
	_u.mutation.SetProbeAvailability6h(v)
	return _u
}

// SetNillableProbeAvailability6h sets the "probe_availability_6h" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableProbeAvailability6h(v *float64) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetProbeAvailability6h(*v)
	}
	return _u
}

// AddProbeAvailability6h adds value to the "probe_availability_6h" field.
func (_u *GroupHealthStateUpdateOne) AddProbeAvailability6h(v float64) *GroupHealthStateUpdateOne {
	_u.mutation.AddProbeAvailability6h(v)
	return _u
}

// SetProbeTtftAvgMs sets the "probe_ttft_avg_ms" field.
func (_u *GroupHealthStateUpdateOne) SetProbeTtftAvgMs(v int) *GroupHealthStateUpdateOne {
	_u.mutation.ResetProbeTtftAvgMs()
	_u.mutation.SetProbeTtftAvgMs(v)
	return _u
}

// SetNillableProbeTtftAvgMs sets the "probe_ttft_avg_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableProbeTtftAvgMs(v *int) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetProbeTtftAvgMs(*v)
	}
	return _u
}

// AddProbeTtftAvgMs adds value to the "probe_ttft_avg_ms" field.
func (_u *GroupHealthStateUpdateOne) AddProbeTtftAvgMs(v int) *GroupHealthStateUpdateOne {
	_u.mutation.AddProbeTtftAvgMs(v)
	return _u
}

// SetProbeTtftP95Ms sets the "probe_ttft_p95_ms" field.
func (_u *GroupHealthStateUpdateOne) SetProbeTtftP95Ms(v int) *GroupHealthStateUpdateOne {
	_u.mutation.ResetProbeTtftP95Ms()
	_u.mutation.SetProbeTtftP95Ms(v)
	return _u
}

// SetNillableProbeTtftP95Ms sets the "probe_ttft_p95_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableProbeTtftP95Ms(v *int) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetProbeTtftP95Ms(*v)
	}
	return _u
}

// AddProbeTtftP95Ms adds value to the "probe_ttft_p95_ms" field.
func (_u *GroupHealthStateUpdateOne) AddProbeTtftP95Ms(v int) *GroupHealthStateUpdateOne {
	_u.mutation.AddProbeTtftP95Ms(v)
	return _u
}

// SetProbeSamples sets the "probe_samples" field.
func (_u *GroupHealthStateUpdateOne) SetProbeSamples(v int) *GroupHealthStateUpdateOne {
	_u.mutation.ResetProbeSamples()
	_u.mutation.SetProbeSamples(v)
	return _u
}

// SetNillableProbeSamples sets the "probe_samples" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableProbeSamples(v *int) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetProbeSamples(*v)
	}
	return _u
}

// AddProbeSamples adds value to the "probe_samples" field.
func (_u *GroupHealthStateUpdateOne) AddProbeSamples(v int) *GroupHealthStateUpdateOne {
	_u.mutation.AddProbeSamples(v)
	return _u
}

// SetRealTtftP50Ms sets the "real_ttft_p50_ms" field.
func (_u *GroupHealthStateUpdateOne) SetRealTtftP50Ms(v int) *GroupHealthStateUpdateOne {
	_u.mutation.ResetRealTtftP50Ms()
	_u.mutation.SetRealTtftP50Ms(v)
	return _u
}

// SetNillableRealTtftP50Ms sets the "real_ttft_p50_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableRealTtftP50Ms(v *int) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetRealTtftP50Ms(*v)
	}
	return _u
}

// AddRealTtftP50Ms adds value to the "real_ttft_p50_ms" field.
func (_u *GroupHealthStateUpdateOne) AddRealTtftP50Ms(v int) *GroupHealthStateUpdateOne {
	_u.mutation.AddRealTtftP50Ms(v)
	return _u
}

// SetRealTtftAvgMs sets the "real_ttft_avg_ms" field.
func (_u *GroupHealthStateUpdateOne) SetRealTtftAvgMs(v int) *GroupHealthStateUpdateOne {
	_u.mutation.ResetRealTtftAvgMs()
	_u.mutation.SetRealTtftAvgMs(v)
	return _u
}

// SetNillableRealTtftAvgMs sets the "real_ttft_avg_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableRealTtftAvgMs(v *int) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetRealTtftAvgMs(*v)
	}
	return _u
}

// AddRealTtftAvgMs adds value to the "real_ttft_avg_ms" field.
func (_u *GroupHealthStateUpdateOne) AddRealTtftAvgMs(v int) *GroupHealthStateUpdateOne {
	_u.mutation.AddRealTtftAvgMs(v)
	return _u
}

// SetRealTtftP95Ms sets the "real_ttft_p95_ms" field.
func (_u *GroupHealthStateUpdateOne) SetRealTtftP95Ms(v int) *GroupHealthStateUpdateOne {
	_u.mutation.ResetRealTtftP95Ms()
	_u.mutation.SetRealTtftP95Ms(v)
	return _u
}

// SetNillableRealTtftP95Ms sets the "real_ttft_p95_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableRealTtftP95Ms(v *int) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetRealTtftP95Ms(*v)
	}
	return _u
}

// AddRealTtftP95Ms adds value to the "real_ttft_p95_ms" field.
func (_u *GroupHealthStateUpdateOne) AddRealTtftP95Ms(v int) *GroupHealthStateUpdateOne {
	_u.mutation.AddRealTtftP95Ms(v)
	return _u
}

// SetRealTtftSamples sets the "real_ttft_samples" field.
func (_u *GroupHealthStateUpdateOne) SetRealTtftSamples(v int) *GroupHealthStateUpdateOne {
	_u.mutation.ResetRealTtftSamples()
	_u.mutation.SetRealTtftSamples(v)
	return _u
}

// SetNillableRealTtftSamples sets the "real_ttft_samples" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableRealTtftSamples(v *int) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetRealTtftSamples(*v)
	}
	return _u
}

// AddRealTtftSamples adds value to the "real_ttft_samples" field.
func (_u *GroupHealthStateUpdateOne) AddRealTtftSamples(v int) *GroupHealthStateUpdateOne {
	_u.mutation.AddRealTtftSamples(v)
	return _u
}

// SetRealAvailability6h sets the "real_availability_6h" field.
func (_u *GroupHealthStateUpdateOne) SetRealAvailability6h(v float64) *GroupHealthStateUpdateOne {
	_u.mutation.ResetRealAvailability6h()
	_u.mutation.SetRealAvailability6h(v)
	return _u
}

// SetNillableRealAvailability6h sets the "real_availability_6h" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableRealAvailability6h(v *float64) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetRealAvailability6h(*v)
	}
	return _u
}

// AddRealAvailability6h adds value to the "real_availability_6h" field.
func (_u *GroupHealthStateUpdateOne) AddRealAvailability6h(v float64) *GroupHealthStateUpdateOne {
	_u.mutation.AddRealAvailability6h(v)
	return _u
}

// SetRealTotalAvgMs sets the "real_total_avg_ms" field.
func (_u *GroupHealthStateUpdateOne) SetRealTotalAvgMs(v int) *GroupHealthStateUpdateOne {
	_u.mutation.ResetRealTotalAvgMs()
	_u.mutation.SetRealTotalAvgMs(v)
	return _u
}

// SetNillableRealTotalAvgMs sets the "real_total_avg_ms" field if the given value is not nil.
func (_u *GroupHealthStateUpdateOne) SetNillableRealTotalAvgMs(v *int) *GroupHealthStateUpdateOne {
	if v != nil {
		_u.SetRealTotalAvgMs(*v)
	}
	return _u
}

// AddRealTotalAvgMs adds value to the "real_total_avg_ms" field.
func (_u *GroupHealthStateUpdateOne) AddRealTotalAvgMs(v int) *GroupHealthStateUpdateOne {
	_u.mutation.AddRealTotalAvgMs(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupHealthStateUpdateOne) SetGroup(v *Group) *GroupHealthStateUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the GroupHealthStateMutation object of the builder.
func (_u *GroupHealthStateUpdateOne) Mutation() *GroupHealthStateMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupHealthStateUpdateOne) ClearGroup() *GroupHealthStateUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the GroupHealthStateUpdate builder.
func (_u *GroupHealthStateUpdateOne) Where(ps ...predicate.GroupHealthState) *GroupHealthStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupHealthStateUpdateOne) Select(field string, fields ...string) *GroupHealthStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupHealthState entity.
func (_u *GroupHealthStateUpdateOne) Save(ctx context.Context) (*GroupHealthState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupHealthStateUpdateOne) SaveX(ctx context.Context) *GroupHealthState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupHealthStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupHealthStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupHealthStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grouphealthstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupHealthStateUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := grouphealthstate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GroupHealthState.status": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupHealthState.group"`)
	}
	return nil
}

func (_u *GroupHealthStateUpdateOne) sqlSave(ctx context.Context) (_node *GroupHealthState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grouphealthstate.Table, grouphealthstate.Columns, sqlgraph.NewFieldSpec(grouphealthstate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupHealthState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grouphealthstate.FieldID)
		for _, f := range fields {
			if !grouphealthstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grouphealthstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grouphealthstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(grouphealthstate.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(grouphealthstate.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(grouphealthstate.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.LastProbeAt(); ok {
		_spec.SetField(grouphealthstate.FieldLastProbeAt, field.TypeTime, value)
	}
	if _u.mutation.LastProbeAtCleared() {
		_spec.ClearField(grouphealthstate.FieldLastProbeAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSuccessAt(); ok {
		_spec.SetField(grouphealthstate.FieldLastSuccessAt, field.TypeTime, value)
	}
	if _u.mutation.LastSuccessAtCleared() {
		_spec.ClearField(grouphealthstate.FieldLastSuccessAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextProbeAt(); ok {
		_spec.SetField(grouphealthstate.FieldNextProbeAt, field.TypeTime, value)
	}
	if _u.mutation.NextProbeAtCleared() {
		_spec.ClearField(grouphealthstate.FieldNextProbeAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureCount(); ok {
		_spec.SetField(grouphealthstate.FieldFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailureCount(); ok {
		_spec.AddField(grouphealthstate.FieldFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProbeTtftMs(); ok {
		_spec.SetField(grouphealthstate.FieldProbeTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProbeTtftMs(); ok {
		_spec.AddField(grouphealthstate.FieldProbeTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProbeAvailability6h(); ok {
		_spec.SetField(grouphealthstate.FieldProbeAvailability6h, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProbeAvailability6h(); ok {
		_spec.AddField(grouphealthstate.FieldProbeAvailability6h, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ProbeTtftAvgMs(); ok {
		_spec.SetField(grouphealthstate.FieldProbeTtftAvgMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProbeTtftAvgMs(); ok {
		_spec.AddField(grouphealthstate.FieldProbeTtftAvgMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProbeTtftP95Ms(); ok {
		_spec.SetField(grouphealthstate.FieldProbeTtftP95Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProbeTtftP95Ms(); ok {
		_spec.AddField(grouphealthstate.FieldProbeTtftP95Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProbeSamples(); ok {
		_spec.SetField(grouphealthstate.FieldProbeSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProbeSamples(); ok {
		_spec.AddField(grouphealthstate.FieldProbeSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RealTtftP50Ms(); ok {
		_spec.SetField(grouphealthstate.FieldRealTtftP50Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRealTtftP50Ms(); ok {
		_spec.AddField(grouphealthstate.FieldRealTtftP50Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RealTtftAvgMs(); ok {
		_spec.SetField(grouphealthstate.FieldRealTtftAvgMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRealTtftAvgMs(); ok {
		_spec.AddField(grouphealthstate.FieldRealTtftAvgMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RealTtftP95Ms(); ok {
		_spec.SetField(grouphealthstate.FieldRealTtftP95Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRealTtftP95Ms(); ok {
		_spec.AddField(grouphealthstate.FieldRealTtftP95Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RealTtftSamples(); ok {
		_spec.SetField(grouphealthstate.FieldRealTtftSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRealTtftSamples(); ok {
		_spec.AddField(grouphealthstate.FieldRealTtftSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RealAvailability6h(); ok {
		_spec.SetField(grouphealthstate.FieldRealAvailability6h, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRealAvailability6h(); ok {
		_spec.AddField(grouphealthstate.FieldRealAvailability6h, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RealTotalAvgMs(); ok {
		_spec.SetField(grouphealthstate.FieldRealTotalAvgMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRealTotalAvgMs(); ok {
		_spec.AddField(grouphealthstate.FieldRealTotalAvgMs, field.TypeInt, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grouphealthstate.GroupTable,
			Columns: []string{grouphealthstate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grouphealthstate.GroupTable,
			Columns: []string{grouphealthstate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GroupHealthState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grouphealthstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
