// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/grouphealthevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupHealthEventUpdate is the builder for updating GroupHealthEvent entities.
type GroupHealthEventUpdate struct {
	config
	hooks    []Hook
	mutation *GroupHealthEventMutation
}

// Where appends a list predicates to the GroupHealthEventUpdate builder.
func (_u *GroupHealthEventUpdate) Where(ps ...predicate.GroupHealthEvent) *GroupHealthEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupHealthEventUpdate) SetUpdatedAt(v time.Time) *GroupHealthEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupHealthEventUpdate) SetGroupID(v int64) *GroupHealthEventUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupHealthEventUpdate) SetNillableGroupID(v *int64) *GroupHealthEventUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *GroupHealthEventUpdate) SetAccountID(v int64) *GroupHealthEventUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *GroupHealthEventUpdate) SetNillableAccountID(v *int64) *GroupHealthEventUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *GroupHealthEventUpdate) AddAccountID(v int64) *GroupHealthEventUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *GroupHealthEventUpdate) ClearAccountID() *GroupHealthEventUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetKind sets the "kind" field.
func (_u *GroupHealthEventUpdate) SetKind(v string) *GroupHealthEventUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *GroupHealthEventUpdate) SetNillableKind(v *string) *GroupHealthEventUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetSuccess sets the "success" field.
func (_u *GroupHealthEventUpdate) SetSuccess(v bool) *GroupHealthEventUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *GroupHealthEventUpdate) SetNillableSuccess(v *bool) *GroupHealthEventUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetIsProbe sets the "is_probe" field.
func (_u *GroupHealthEventUpdate) SetIsProbe(v bool) *GroupHealthEventUpdate {
	_u.mutation.SetIsProbe(v)
	return _u
}

// SetNillableIsProbe sets the "is_probe" field if the given value is not nil.
func (_u *GroupHealthEventUpdate) SetNillableIsProbe(v *bool) *GroupHealthEventUpdate {
	if v != nil {
		_u.SetIsProbe(*v)
	}
	return _u
}

// SetSemanticStarted sets the "semantic_started" field.
func (_u *GroupHealthEventUpdate) SetSemanticStarted(v bool) *GroupHealthEventUpdate {
	_u.mutation.SetSemanticStarted(v)
	return _u
}

// SetNillableSemanticStarted sets the "semantic_started" field if the given value is not nil.
func (_u *GroupHealthEventUpdate) SetNillableSemanticStarted(v *bool) *GroupHealthEventUpdate {
	if v != nil {
		_u.SetSemanticStarted(*v)
	}
	return _u
}

// SetErrorCategory sets the "error_category" field.
func (_u *GroupHealthEventUpdate) SetErrorCategory(v string) *GroupHealthEventUpdate {
	_u.mutation.SetErrorCategory(v)
	return _u
}

// SetNillableErrorCategory sets the "error_category" field if the given value is not nil.
func (_u *GroupHealthEventUpdate) SetNillableErrorCategory(v *string) *GroupHealthEventUpdate {
	if v != nil {
		_u.SetErrorCategory(*v)
	}
	return _u
}

// ClearErrorCategory clears the value of the "error_category" field.
func (_u *GroupHealthEventUpdate) ClearErrorCategory() *GroupHealthEventUpdate {
	_u.mutation.ClearErrorCategory()
	return _u
}

// SetTtftMs sets the "ttft_ms" field.
func (_u *GroupHealthEventUpdate) SetTtftMs(v int) *GroupHealthEventUpdate {
	_u.mutation.ResetTtftMs()
	_u.mutation.SetTtftMs(v)
	return _u
}

// SetNillableTtftMs sets the "ttft_ms" field if the given value is not nil.
func (_u *GroupHealthEventUpdate) SetNillableTtftMs(v *int) *GroupHealthEventUpdate {
	if v != nil {
		_u.SetTtftMs(*v)
	}
	return _u
}

// AddTtftMs adds value to the "ttft_ms" field.
func (_u *GroupHealthEventUpdate) AddTtftMs(v int) *GroupHealthEventUpdate {
	_u.mutation.AddTtftMs(v)
	return _u
}

// SetTotalMs sets the "total_ms" field.
func (_u *GroupHealthEventUpdate) SetTotalMs(v int) *GroupHealthEventUpdate {
	_u.mutation.ResetTotalMs()
	_u.mutation.SetTotalMs(v)
	return _u
}

// SetNillableTotalMs sets the "total_ms" field if the given value is not nil.
func (_u *GroupHealthEventUpdate) SetNillableTotalMs(v *int) *GroupHealthEventUpdate {
	if v != nil {
		_u.SetTotalMs(*v)
	}
	return _u
}

// AddTotalMs adds value to the "total_ms" field.
func (_u *GroupHealthEventUpdate) AddTotalMs(v int) *GroupHealthEventUpdate {
	_u.mutation.AddTotalMs(v)
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *GroupHealthEventUpdate) SetObservedAt(v time.Time) *GroupHealthEventUpdate {
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *GroupHealthEventUpdate) SetNillableObservedAt(v *time.Time) *GroupHealthEventUpdate {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *GroupHealthEventUpdate) SetErrorMessage(v string) *GroupHealthEventUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *GroupHealthEventUpdate) SetNillableErrorMessage(v *string) *GroupHealthEventUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *GroupHealthEventUpdate) ClearErrorMessage() *GroupHealthEventUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupHealthEventUpdate) SetGroup(v *Group) *GroupHealthEventUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the GroupHealthEventMutation object of the builder.
func (_u *GroupHealthEventUpdate) Mutation() *GroupHealthEventMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupHealthEventUpdate) ClearGroup() *GroupHealthEventUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupHealthEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupHealthEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupHealthEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupHealthEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupHealthEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grouphealthevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupHealthEventUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := grouphealthevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "GroupHealthEvent.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCategory(); ok {
		if err := grouphealthevent.ErrorCategoryValidator(v); err != nil {
			return &ValidationError{Name: "error_category", err: fmt.Errorf(`ent: validator failed for field "GroupHealthEvent.error_category": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupHealthEvent.group"`)
	}
	return nil
}

func (_u *GroupHealthEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grouphealthevent.Table, grouphealthevent.Columns, sqlgraph.NewFieldSpec(grouphealthevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grouphealthevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(grouphealthevent.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(grouphealthevent.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(grouphealthevent.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(grouphealthevent.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(grouphealthevent.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsProbe(); ok {
		_spec.SetField(grouphealthevent.FieldIsProbe, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SemanticStarted(); ok {
		_spec.SetField(grouphealthevent.FieldSemanticStarted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ErrorCategory(); ok {
		_spec.SetField(grouphealthevent.FieldErrorCategory, field.TypeString, value)
	}
	if _u.mutation.ErrorCategoryCleared() {
		_spec.ClearField(grouphealthevent.FieldErrorCategory, field.TypeString)
	}
	if value, ok := _u.mutation.TtftMs(); ok {
		_spec.SetField(grouphealthevent.FieldTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTtftMs(); ok {
		_spec.AddField(grouphealthevent.FieldTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalMs(); ok {
		_spec.SetField(grouphealthevent.FieldTotalMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalMs(); ok {
		_spec.AddField(grouphealthevent.FieldTotalMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(grouphealthevent.FieldObservedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(grouphealthevent.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(grouphealthevent.FieldErrorMessage, field.TypeString)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grouphealthevent.GroupTable,
			Columns: []string{grouphealthevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grouphealthevent.GroupTable,
			Columns: []string{grouphealthevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grouphealthevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupHealthEventUpdateOne is the builder for updating a single GroupHealthEvent entity.
type GroupHealthEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupHealthEventMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupHealthEventUpdateOne) SetUpdatedAt(v time.Time) *GroupHealthEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupHealthEventUpdateOne) SetGroupID(v int64) *GroupHealthEventUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupHealthEventUpdateOne) SetNillableGroupID(v *int64) *GroupHealthEventUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *GroupHealthEventUpdateOne) SetAccountID(v int64) *GroupHealthEventUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *GroupHealthEventUpdateOne) SetNillableAccountID(v *int64) *GroupHealthEventUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *GroupHealthEventUpdateOne) AddAccountID(v int64) *GroupHealthEventUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *GroupHealthEventUpdateOne) ClearAccountID() *GroupHealthEventUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetKind sets the "kind" field.
func (_u *GroupHealthEventUpdateOne) SetKind(v string) *GroupHealthEventUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *GroupHealthEventUpdateOne) SetNillableKind(v *string) *GroupHealthEventUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetSuccess sets the "success" field.
func (_u *GroupHealthEventUpdateOne) SetSuccess(v bool) *GroupHealthEventUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *GroupHealthEventUpdateOne) SetNillableSuccess(v *bool) *GroupHealthEventUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetIsProbe sets the "is_probe" field.
func (_u *GroupHealthEventUpdateOne) SetIsProbe(v bool) *GroupHealthEventUpdateOne {
	_u.mutation.SetIsProbe(v)
	return _u
}

// SetNillableIsProbe sets the "is_probe" field if the given value is not nil.
func (_u *GroupHealthEventUpdateOne) SetNillableIsProbe(v *bool) *GroupHealthEventUpdateOne {
	if v != nil {
		_u.SetIsProbe(*v)
	}
	return _u
}

// SetSemanticStarted sets the "semantic_started" field.
func (_u *GroupHealthEventUpdateOne) SetSemanticStarted(v bool) *GroupHealthEventUpdateOne {
	_u.mutation.SetSemanticStarted(v)
	return _u
}

// SetNillableSemanticStarted sets the "semantic_started" field if the given value is not nil.
func (_u *GroupHealthEventUpdateOne) SetNillableSemanticStarted(v *bool) *GroupHealthEventUpdateOne {
	if v != nil {
		_u.SetSemanticStarted(*v)
	}
	return _u
}

// SetErrorCategory sets the "error_category" field.
func (_u *GroupHealthEventUpdateOne) SetErrorCategory(v string) *GroupHealthEventUpdateOne {
	_u.mutation.SetErrorCategory(v)
	return _u
}

// SetNillableErrorCategory sets the "error_category" field if the given value is not nil.
func (_u *GroupHealthEventUpdateOne) SetNillableErrorCategory(v *string) *GroupHealthEventUpdateOne {
	if v != nil {
		_u.SetErrorCategory(*v)
	}
	return _u
}

// ClearErrorCategory clears the value of the "error_category" field.
func (_u *GroupHealthEventUpdateOne) ClearErrorCategory() *GroupHealthEventUpdateOne {
	_u.mutation.ClearErrorCategory()
	return _u
}

// SetTtftMs sets the "ttft_ms" field.
func (_u *GroupHealthEventUpdateOne) SetTtftMs(v int) *GroupHealthEventUpdateOne {
	_u.mutation.ResetTtftMs()
	_u.mutation.SetTtftMs(v)
	return _u
}

// SetNillableTtftMs sets the "ttft_ms" field if the given value is not nil.
func (_u *GroupHealthEventUpdateOne) SetNillableTtftMs(v *int) *GroupHealthEventUpdateOne {
	if v != nil {
		_u.SetTtftMs(*v)
	}
	return _u
}

// AddTtftMs adds value to the "ttft_ms" field.
func (_u *GroupHealthEventUpdateOne) AddTtftMs(v int) *GroupHealthEventUpdateOne {
	_u.mutation.AddTtftMs(v)
	return _u
}

// SetTotalMs sets the "total_ms" field.
func (_u *GroupHealthEventUpdateOne) SetTotalMs(v int) *GroupHealthEventUpdateOne {
	_u.mutation.ResetTotalMs()
	_u.mutation.SetTotalMs(v)
	return _u
}

// SetNillableTotalMs sets the "total_ms" field if the given value is not nil.
func (_u *GroupHealthEventUpdateOne) SetNillableTotalMs(v *int) *GroupHealthEventUpdateOne {
	if v != nil {
		_u.SetTotalMs(*v)
	}
	return _u
}

// AddTotalMs adds value to the "total_ms" field.
func (_u *GroupHealthEventUpdateOne) AddTotalMs(v int) *GroupHealthEventUpdateOne {
	_u.mutation.AddTotalMs(v)
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *GroupHealthEventUpdateOne) SetObservedAt(v time.Time) *GroupHealthEventUpdateOne {
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *GroupHealthEventUpdateOne) SetNillableObservedAt(v *time.Time) *GroupHealthEventUpdateOne {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *GroupHealthEventUpdateOne) SetErrorMessage(v string) *GroupHealthEventUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *GroupHealthEventUpdateOne) SetNillableErrorMessage(v *string) *GroupHealthEventUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *GroupHealthEventUpdateOne) ClearErrorMessage() *GroupHealthEventUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupHealthEventUpdateOne) SetGroup(v *Group) *GroupHealthEventUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the GroupHealthEventMutation object of the builder.
func (_u *GroupHealthEventUpdateOne) Mutation() *GroupHealthEventMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupHealthEventUpdateOne) ClearGroup() *GroupHealthEventUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the GroupHealthEventUpdate builder.
func (_u *GroupHealthEventUpdateOne) Where(ps ...predicate.GroupHealthEvent) *GroupHealthEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupHealthEventUpdateOne) Select(field string, fields ...string) *GroupHealthEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupHealthEvent entity.
func (_u *GroupHealthEventUpdateOne) Save(ctx context.Context) (*GroupHealthEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupHealthEventUpdateOne) SaveX(ctx context.Context) *GroupHealthEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupHealthEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupHealthEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupHealthEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grouphealthevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupHealthEventUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := grouphealthevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "GroupHealthEvent.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCategory(); ok {
		if err := grouphealthevent.ErrorCategoryValidator(v); err != nil {
			return &ValidationError{Name: "error_category", err: fmt.Errorf(`ent: validator failed for field "GroupHealthEvent.error_category": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupHealthEvent.group"`)
	}
	return nil
}

func (_u *GroupHealthEventUpdateOne) sqlSave(ctx context.Context) (_node *GroupHealthEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grouphealthevent.Table, grouphealthevent.Columns, sqlgraph.NewFieldSpec(grouphealthevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupHealthEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grouphealthevent.FieldID)
		for _, f := range fields {
			if !grouphealthevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grouphealthevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grouphealthevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(grouphealthevent.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(grouphealthevent.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(grouphealthevent.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(grouphealthevent.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(grouphealthevent.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsProbe(); ok {
		_spec.SetField(grouphealthevent.FieldIsProbe, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SemanticStarted(); ok {
		_spec.SetField(grouphealthevent.FieldSemanticStarted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ErrorCategory(); ok {
		_spec.SetField(grouphealthevent.FieldErrorCategory, field.TypeString, value)
	}
	if _u.mutation.ErrorCategoryCleared() {
		_spec.ClearField(grouphealthevent.FieldErrorCategory, field.TypeString)
	}
	if value, ok := _u.mutation.TtftMs(); ok {
		_spec.SetField(grouphealthevent.FieldTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTtftMs(); ok {
		_spec.AddField(grouphealthevent.FieldTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalMs(); ok {
		_spec.SetField(grouphealthevent.FieldTotalMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalMs(); ok {
		_spec.AddField(grouphealthevent.FieldTotalMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(grouphealthevent.FieldObservedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(grouphealthevent.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(grouphealthevent.FieldErrorMessage, field.TypeString)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grouphealthevent.GroupTable,
			Columns: []string{grouphealthevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   grouphealthevent.GroupTable,
			Columns: []string{grouphealthevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GroupHealthEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grouphealthevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
